const Question = require('../models/question.model');

const questions = [
  // ─────────────────────────────────────────
  // BEHAVIORAL (20)
  // ─────────────────────────────────────────
  {
    content: 'Hãy kể về một lần bạn phải làm việc dưới áp lực lớn. Bạn đã xử lý tình huống đó như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Pressure & Stress',
    tags: ['pressure', 'stress management', 'problem solving'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả tình huống cụ thể, áp lực đến từ đâu (deadline, yêu cầu thay đổi...). Giải thích cách bạn ưu tiên công việc, giao tiếp với team, và kết quả đạt được.',
    hints: ['Dùng phương pháp STAR (Situation, Task, Action, Result)', 'Nêu rõ kết quả cụ thể'],
  },
  {
    content: 'Kể về một lần bạn thất bại trong dự án. Bạn đã học được gì từ đó?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Learning from Failure',
    tags: ['failure', 'growth mindset', 'self-awareness'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả thất bại một cách trung thực, không đổ lỗi cho người khác. Tập trung vào bài học rút ra và những thay đổi bạn thực hiện sau đó.',
    hints: ['Chọn thất bại thực sự có ý nghĩa, không quá nhỏ nhặt', 'Nhấn mạnh vào hành động cải thiện'],
  },
  {
    content: 'Bạn xử lý xung đột với đồng nghiệp như thế nào? Hãy chia sẻ một ví dụ cụ thể.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Conflict Resolution',
    tags: ['conflict', 'teamwork', 'communication'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả xung đột, cách bạn tiếp cận đồng nghiệp một cách bình tĩnh, lắng nghe quan điểm của họ, và tìm giải pháp chung.',
    hints: ['Thể hiện sự trưởng thành và kỹ năng lắng nghe', 'Không nói xấu đồng nghiệp'],
  },
  {
    content: 'Mô tả dự án khó khăn nhất bạn từng tham gia. Vai trò của bạn là gì và kết quả ra sao?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Project Experience',
    tags: ['project', 'challenge', 'achievement'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả rõ dự án, thách thức cụ thể (technical debt, yêu cầu mơ hồ, deadline ngắn...), đóng góp cá nhân, và kết quả đo lường được.',
    hints: ['Chọn dự án có impact rõ ràng', 'Nêu metrics cụ thể nếu có'],
  },
  {
    content: 'Kể về một lần bạn thể hiện khả năng lãnh đạo, dù bạn không phải là manager.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Leadership',
    tags: ['leadership', 'initiative', 'influence'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả tình huống bạn chủ động dẫn dắt nhóm, đưa ra hướng giải quyết, hoặc motivate đồng đội mà không cần chức danh.',
    hints: ['Leadership không cần chức danh', 'Tập trung vào hành động chủ động của bạn'],
  },
  {
    content: 'Khi có nhiều deadline cùng lúc, bạn sắp xếp ưu tiên công việc như thế nào?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Time Management',
    tags: ['prioritization', 'time management', 'organization'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến framework bạn dùng (Eisenhower Matrix, MoSCoW...), cách giao tiếp với stakeholders khi cần điều chỉnh deadline.',
    hints: ['Nêu phương pháp cụ thể', 'Đề cập đến việc giao tiếp khi quá tải'],
  },
  {
    content: 'Hãy kể về một lần bạn phải học một công nghệ mới trong thời gian ngắn. Bạn tiếp cận như thế nào?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Learning Agility',
    tags: ['learning', 'adaptability', 'self-improvement'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả cách bạn xác định kiến thức cần thiết, nguồn tài liệu bạn dùng, cách bạn thực hành và áp dụng nhanh vào dự án.',
    hints: ['Thể hiện tính chủ động trong học tập', 'Đề cập đến cách bạn xử lý khi gặp khó khăn'],
  },
  {
    content: 'Kể về một lần bạn không đồng ý với quyết định của manager. Bạn xử lý thế nào?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Upward Management',
    tags: ['communication', 'disagreement', 'professionalism'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn trình bày quan điểm dựa trên data/logic, lắng nghe lý do của manager, và chấp nhận hoặc thuyết phục một cách chuyên nghiệp.',
    hints: ['Tránh tỏ ra bướng bỉnh', 'Thể hiện tư duy phản biện có xây dựng'],
  },
  {
    content: 'Bạn phản ứng như thế nào khi nhận được feedback tiêu cực về code của mình?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Receiving Feedback',
    tags: ['feedback', 'growth', 'ego'],
    expectedDuration: 90,
    sampleAnswer: 'Thể hiện sự cởi mở với feedback, đặt câu hỏi để hiểu rõ, và mô tả cách bạn cải thiện dựa trên feedback đó.',
    hints: ['Tách cái tôi khỏi code', 'Feedback là cơ hội học tập'],
  },
  {
    content: 'Hãy kể về một lần bạn giúp đỡ đồng nghiệp vượt qua khó khăn kỹ thuật.',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Collaboration',
    tags: ['helping', 'teamwork', 'knowledge sharing'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả vấn đề đồng nghiệp gặp phải, cách bạn tiếp cận để giải thích/hỗ trợ, và kết quả của sự hợp tác đó.',
    hints: ['Thể hiện kỹ năng giải thích và kiên nhẫn', 'Nêu impact của sự giúp đỡ'],
  },
  {
    content: 'Thành tựu kỹ thuật lớn nhất của bạn cho đến nay là gì?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Achievement',
    tags: ['achievement', 'pride', 'impact'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả thành tựu với context rõ ràng, đóng góp cá nhân, và impact đo lường được (tăng performance X%, giảm bug Y%).',
    hints: ['Dùng số liệu cụ thể nếu có', 'Giải thích tại sao bạn tự hào về điều này'],
  },
  {
    content: 'Khi nhận yêu cầu mơ hồ từ khách hàng, bạn làm gì để làm rõ trước khi bắt tay vào code?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Requirement Clarification',
    tags: ['communication', 'requirements', 'proactive'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến việc đặt câu hỏi làm rõ, viết document tóm tắt hiểu biết, xác nhận lại với stakeholder trước khi bắt đầu.',
    hints: ['Thể hiện tính proactive', 'Đề cập đến risk của việc không làm rõ'],
  },
  {
    content: 'Kể về một lần bạn vô tình gây ra bug trên production. Bạn xử lý tình huống đó như thế nào?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Incident Handling',
    tags: ['bug', 'production', 'responsibility', 'crisis'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả incident, cách bạn nhận trách nhiệm, các bước bạn thực hiện để hotfix, và cách ngăn tái phát (post-mortem, tests...).',
    hints: ['Không giấu hay đổ lỗi', 'Tập trung vào quy trình xử lý và phòng ngừa'],
  },
  {
    content: 'Hãy kể về một lần bạn cải thiện quy trình làm việc của team.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Process Improvement',
    tags: ['process', 'efficiency', 'initiative'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả vấn đề trong quy trình hiện tại, đề xuất bạn đưa ra, cách bạn thuyết phục team, và kết quả sau khi thực hiện.',
    hints: ['Thể hiện tư duy cải tiến liên tục', 'Dùng số liệu trước và sau'],
  },
  {
    content: 'Mô tả cách bạn xử lý một stakeholder khó tính hoặc thường xuyên thay đổi yêu cầu.',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Stakeholder Management',
    tags: ['stakeholder', 'communication', 'professionalism'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn thiết lập expectations, document các thay đổi, và maintain mối quan hệ chuyên nghiệp dù có áp lực.',
    hints: ['Không nói xấu stakeholder', 'Thể hiện kỹ năng đàm phán và giao tiếp'],
  },
  {
    content: 'Kể về một quyết định khó khăn bạn phải đưa ra trong dự án. Bạn cân nhắc những yếu tố gì?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Decision Making',
    tags: ['decision making', 'trade-offs', 'judgment'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả các lựa chọn, trade-offs kỹ thuật/business, cách bạn thu thập thông tin, và kết quả của quyết định đó.',
    hints: ['Thể hiện tư duy có cấu trúc', 'Đề cập đến các stakeholder liên quan'],
  },
  {
    content: 'Hãy kể về một lần bạn làm việc vượt mức yêu cầu để đảm bảo dự án thành công.',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Work Ethic',
    tags: ['dedication', 'ownership', 'going beyond'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả tình huống, lý do bạn chọn đi xa hơn, và impact của hành động đó lên team/dự án.',
    hints: ['Thể hiện ownership và trách nhiệm', 'Không quá đề cao bản thân'],
  },
  {
    content: 'Bạn duy trì động lực như thế nào khi làm những công việc lặp đi lặp lại hoặc nhàm chán?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Motivation',
    tags: ['motivation', 'attitude', 'consistency'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến việc tìm ý nghĩa trong công việc, tự đặt thử thách mới, hoặc kết nối công việc với mục tiêu lớn hơn.',
    hints: ['Thể hiện thái độ tích cực', 'Tránh nói bạn không bao giờ nhàm chán'],
  },
  {
    content: 'Kể về một lần công ty/team thay đổi hướng đột ngột. Bạn thích nghi như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Adaptability',
    tags: ['change management', 'flexibility', 'adaptability'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả sự thay đổi, cảm xúc ban đầu, cách bạn điều chỉnh mindset, và những gì bạn làm để thích nghi nhanh chóng.',
    hints: ['Thể hiện tính linh hoạt', 'Đề cập đến cách bạn giúp người khác thích nghi'],
  },
  {
    content: 'Hãy kể về một lần bạn mentoring junior developer. Bạn tiếp cận như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Mentoring',
    tags: ['mentoring', 'teaching', 'leadership', 'patience'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn assess trình độ của junior, xây dựng kế hoạch hướng dẫn, balance giữa cho câu trả lời và để họ tự tìm.',
    hints: ['Thể hiện sự kiên nhẫn và khả năng giải thích', 'Nêu kết quả phát triển của mentee'],
  },

  // ─────────────────────────────────────────
  // TECHNICAL — FRONTEND (15)
  // ─────────────────────────────────────────
  {
    content: 'Virtual DOM là gì? Tại sao React sử dụng Virtual DOM và nó giúp cải thiện performance như thế nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    tags: ['react', 'virtual dom', 'performance', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Virtual DOM là bản sao nhẹ của Real DOM trong memory. React so sánh Virtual DOM mới và cũ (diffing), chỉ cập nhật phần thay đổi lên Real DOM (reconciliation), tránh re-render toàn bộ trang.',
    hints: ['Giải thích diffing algorithm', 'So sánh với Real DOM manipulation trực tiếp'],
  },
  {
    content: 'Giải thích sự khác biệt giữa useMemo và useCallback trong React. Khi nào nên dùng cái nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    tags: ['react', 'hooks', 'performance', 'memoization'],
    expectedDuration: 120,
    sampleAnswer: 'useMemo memoize giá trị tính toán, useCallback memoize function reference. Dùng useMemo khi có expensive computation, useCallback khi truyền callback xuống child component để tránh re-render không cần thiết.',
    hints: ['Nêu ví dụ cụ thể cho từng hook', 'Đề cập đến khi nào KHÔNG nên dùng (premature optimization)'],
  },
  {
    content: 'Event bubbling và event capturing trong JavaScript là gì? Sự khác biệt giữa stopPropagation và preventDefault?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    tags: ['javascript', 'events', 'dom', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Capturing: event đi từ root xuống target. Bubbling: event đi từ target lên root. stopPropagation ngừng lan truyền event, preventDefault ngăn hành vi mặc định của browser (submit form, follow link...).',
    hints: ['Vẽ sơ đồ nếu cần', 'Nêu ví dụ thực tế về event delegation'],
  },
  {
    content: 'Closure trong JavaScript là gì? Cho ví dụ thực tế về việc sử dụng closure.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    tags: ['javascript', 'closure', 'scope', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Closure là function có thể truy cập variables từ outer scope sau khi outer function đã return. Ví dụ: counter function, module pattern, function factories.',
    hints: ['Giải thích lexical scope trước', 'Nêu ví dụ về closure trong vòng lặp (bug thường gặp)'],
  },
  {
    content: 'Giải thích Event Loop trong JavaScript. Tại sao JavaScript là single-threaded nhưng vẫn có thể xử lý async?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'JavaScript',
    tags: ['javascript', 'event loop', 'async', 'call stack'],
    expectedDuration: 150,
    sampleAnswer: 'Call Stack xử lý synchronous code. Web APIs xử lý async (setTimeout, fetch...). Callback Queue chứa các callback. Event Loop liên tục kiểm tra khi Call Stack rỗng sẽ push callback từ Queue vào Stack.',
    hints: ['Mô tả rõ Call Stack, Callback Queue, Microtask Queue', 'Giải thích tại sao Promise có priority cao hơn setTimeout'],
  },
  {
    content: 'So sánh Promise và async/await. Ưu nhược điểm của mỗi cách và khi nào nên dùng cái nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    tags: ['javascript', 'promise', 'async', 'await'],
    expectedDuration: 120,
    sampleAnswer: 'Promise: chain được, xử lý parallel tốt với Promise.all. async/await: code đọc dễ hơn, error handling với try/catch tự nhiên hơn. async/await build trên Promise, không loại trừ nhau.',
    hints: ['Đề cập đến Promise.all, Promise.race', 'Nêu cạm bẫy của async/await trong vòng lặp'],
  },
  {
    content: 'CSS Specificity hoạt động như thế nào? Giải thích thứ tự ưu tiên của các selector.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'CSS',
    tags: ['css', 'specificity', 'selector', 'frontend'],
    expectedDuration: 90,
    sampleAnswer: 'Inline style (1,0,0,0) > ID (0,1,0,0) > Class/Pseudo-class/Attribute (0,0,1,0) > Element (0,0,0,1). !important override tất cả. Tính toán bằng cách cộng điểm từng loại selector.',
    hints: ['Dùng ví dụ số điểm cụ thể', 'Đề cập đến !important và tại sao nên tránh'],
  },
  {
    content: 'Sự khác biệt giữa SSR (Server-Side Rendering) và CSR (Client-Side Rendering)? Next.js giải quyết vấn đề gì?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Frontend Architecture',
    tags: ['ssr', 'csr', 'nextjs', 'performance', 'seo'],
    expectedDuration: 120,
    sampleAnswer: 'CSR: browser download JS rồi render, SEO kém, TTFB nhanh nhưng FCP chậm. SSR: server render HTML hoàn chỉnh, SEO tốt, FCP nhanh. Next.js hỗ trợ cả hai và thêm ISR, SSG.',
    hints: ['Đề cập đến SEO và performance metrics', 'Nêu trade-offs của từng approach'],
  },
  {
    content: 'CORS là gì? Tại sao browser chặn cross-origin request và cách xử lý CORS trong dự án thực tế?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Web Security',
    tags: ['cors', 'security', 'http', 'frontend', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'CORS là cơ chế bảo mật của browser ngăn request từ origin khác. Server cần set Access-Control-Allow-Origin header. Preflight request (OPTIONS) được gửi trước complex requests.',
    hints: ['Giải thích Same-Origin Policy', 'Đề cập đến simple vs preflight request'],
  },
  {
    content: 'Giải thích sự khác biệt giữa null, undefined và undeclared trong JavaScript.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'JavaScript',
    tags: ['javascript', 'null', 'undefined', 'types'],
    expectedDuration: 90,
    sampleAnswer: 'undefined: variable được khai báo nhưng chưa gán giá trị. null: giá trị rỗng có chủ đích. undeclared: variable chưa được khai báo (gây ReferenceError). typeof null === "object" là bug của JS.',
    hints: ['Nêu ví dụ code cụ thể', 'Đề cập đến == vs === khi so sánh'],
  },
  {
    content: 'Webpack là gì và nó hoạt động như thế nào? Giải thích các khái niệm: entry, output, loader, plugin.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Build Tools',
    tags: ['webpack', 'bundler', 'build tools', 'frontend'],
    expectedDuration: 150,
    sampleAnswer: 'Webpack là module bundler. Entry: điểm bắt đầu. Output: file bundle đầu ra. Loader: transform files (babel-loader, css-loader). Plugin: mở rộng chức năng (HtmlWebpackPlugin, MiniCssExtractPlugin).',
    hints: ['Đề cập đến tree shaking, code splitting', 'So sánh với Vite nếu biết'],
  },
  {
    content: 'TypeScript mang lại lợi ích gì so với JavaScript thuần? Giải thích về generics và type guards.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'TypeScript',
    tags: ['typescript', 'types', 'generics', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'TypeScript: type safety, better IDE support, catch bugs compile time. Generics cho phép tái sử dụng code với nhiều type. Type guards (typeof, instanceof, custom) narrow type trong runtime.',
    hints: ['Nêu ví dụ generic function cụ thể', 'Đề cập đến type vs interface'],
  },
  {
    content: 'React component lifecycle hoạt động như thế nào? So sánh class component lifecycle với hooks.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    tags: ['react', 'lifecycle', 'hooks', 'useEffect'],
    expectedDuration: 120,
    sampleAnswer: 'Class: constructor → render → componentDidMount → componentDidUpdate → componentWillUnmount. Hooks: useEffect(() => {}, []) tương đương didMount, useEffect(() => {}, [dep]) tương đương didUpdate, cleanup function tương đương willUnmount.',
    hints: ['Vẽ sơ đồ lifecycle nếu có thể', 'Giải thích dependency array của useEffect'],
  },
  {
    content: 'Giải thích cách hoạt động của this trong JavaScript. Sự khác biệt giữa arrow function và regular function.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    tags: ['javascript', 'this', 'arrow function', 'scope'],
    expectedDuration: 120,
    sampleAnswer: 'this trong regular function phụ thuộc vào cách gọi (implicit, explicit binding, new). Arrow function không có this riêng, kế thừa từ lexical scope. Không dùng arrow function làm method của object.',
    hints: ['Nêu 4 rules binding: default, implicit, explicit, new', 'Ví dụ về call, apply, bind'],
  },
  {
    content: 'Web Performance Optimization: những kỹ thuật nào bạn thường dùng để tối ưu tốc độ tải trang?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Performance',
    tags: ['performance', 'optimization', 'frontend', 'web vitals'],
    expectedDuration: 150,
    sampleAnswer: 'Code splitting, lazy loading, image optimization (WebP, srcset), caching (HTTP cache, Service Worker), minification, tree shaking, CDN, preload/prefetch, reduce render-blocking resources.',
    hints: ['Đề cập đến Core Web Vitals (LCP, FID, CLS)', 'Nêu tools đo lường (Lighthouse, WebPageTest)'],
  },

  // ─────────────────────────────────────────
  // TECHNICAL — BACKEND (15)
  // ─────────────────────────────────────────
  {
    content: 'REST API là gì? Giải thích các nguyên tắc RESTful và sự khác biệt với GraphQL.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'API Design',
    tags: ['rest', 'api', 'http', 'graphql', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'REST: stateless, uniform interface, resource-based URL, HTTP methods. GraphQL: query linh hoạt, single endpoint, tránh over/under-fetching. REST phù hợp với public API, GraphQL tốt cho complex data requirements.',
    hints: ['Giải thích 6 constraints của REST', 'Nêu ví dụ URL design tốt vs xấu'],
  },
  {
    content: 'Database indexing hoạt động như thế nào? Khi nào nên và không nên tạo index?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    tags: ['database', 'index', 'performance', 'mongodb', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'Index là cấu trúc dữ liệu (B-tree) tăng tốc query. Nên index: fields thường query/sort/join. Không nên: bảng nhỏ, fields ít unique, bảng thường xuyên write nhiều (index làm chậm write).',
    hints: ['Giải thích B-tree index', 'Đề cập đến compound index và selectivity'],
  },
  {
    content: 'SQL vs NoSQL: khi nào chọn cái nào? Ưu nhược điểm của mỗi loại.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    tags: ['sql', 'nosql', 'database', 'mongodb', 'postgresql'],
    expectedDuration: 120,
    sampleAnswer: 'SQL: ACID, schema cứng, quan hệ phức tạp, reporting. NoSQL: schema linh hoạt, scale horizontal, dữ liệu phi cấu trúc/semi-structured. Chọn dựa trên data model, query pattern, consistency requirements.',
    hints: ['Nêu ví dụ use case cụ thể cho mỗi loại', 'Đề cập đến CAP theorem'],
  },
  {
    content: 'Middleware trong Express.js là gì? Giải thích request lifecycle và cách error handling middleware hoạt động.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Node.js',
    tags: ['nodejs', 'express', 'middleware', 'backend'],
    expectedDuration: 90,
    sampleAnswer: 'Middleware là function có (req, res, next). Được thực thi theo thứ tự. Error middleware có 4 params (err, req, res, next). Request đi qua từng middleware theo thứ tự mount.',
    hints: ['Vẽ flow của request qua các middleware', 'Đề cập đến next(err) để pass lỗi'],
  },
  {
    content: 'Caching là gì? Giải thích các loại cache và chiến lược cache invalidation.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Caching',
    tags: ['cache', 'redis', 'performance', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'Cache-aside, Read-through, Write-through, Write-behind. Invalidation: TTL-based, event-driven, cache busting. Redis cho distributed cache. Vấn đề: cache stampede, thundering herd, stale data.',
    hints: ['Giải thích trade-off giữa consistency và performance', 'Đề cập đến CDN cache vs application cache'],
  },
  {
    content: 'ACID properties trong database là gì? Giải thích transaction và isolation levels.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Database',
    tags: ['database', 'acid', 'transaction', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Atomicity: tất cả hoặc không. Consistency: data luôn valid. Isolation: transaction không ảnh hưởng nhau. Durability: data persist sau commit. Isolation levels: Read Uncommitted, Read Committed, Repeatable Read, Serializable.',
    hints: ['Nêu ví dụ về dirty read, phantom read', 'Giải thích trade-off giữa isolation và performance'],
  },
  {
    content: 'N+1 query problem là gì? Làm thế nào để phát hiện và giải quyết?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    tags: ['database', 'n+1', 'orm', 'performance', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'N+1: 1 query lấy N records, sau đó N queries cho mỗi record (tổng N+1 queries). Giải quyết: eager loading (populate/join), dataloader (batch), denormalization. Phát hiện bằng query logger.',
    hints: ['Nêu ví dụ cụ thể với code', 'Đề cập đến Mongoose populate vs aggregation'],
  },
  {
    content: 'Message Queue là gì? Khi nào nên dùng? So sánh Bull, RabbitMQ và Kafka.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Message Queue',
    tags: ['queue', 'bull', 'rabbitmq', 'kafka', 'async', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Queue: decouple services, handle async tasks, retry failed jobs. Bull: đơn giản, Redis-based, tốt cho Node.js. RabbitMQ: reliable messaging, routing phức tạp. Kafka: high throughput, event streaming, replay.',
    hints: ['Đề cập đến dead letter queue, retry mechanism', 'Nêu ví dụ use case: email, notification, video processing'],
  },
  {
    content: 'JWT (JSON Web Token) hoạt động như thế nào? Sự khác biệt giữa access token và refresh token.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Authentication',
    tags: ['jwt', 'auth', 'security', 'token', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'JWT gồm header.payload.signature. Stateless, không cần store session. Access token: short-lived, dùng mỗi request. Refresh token: long-lived, chỉ dùng để lấy access token mới. Store refresh token ở httpOnly cookie.',
    hints: ['Giải thích tại sao không nên store JWT ở localStorage', 'Đề cập đến token rotation'],
  },
  {
    content: 'Rate limiting là gì? Giải thích các thuật toán: Token Bucket, Fixed Window, Sliding Window.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'API Security',
    tags: ['rate limit', 'security', 'algorithm', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Fixed Window: đếm requests trong window cố định, vấn đề burst ở ranh giới. Sliding Window: chính xác hơn, tốn memory hơn. Token Bucket: flexible, cho phép burst nhỏ. Leaky Bucket: smooth out traffic.',
    hints: ['Vẽ diagram cho từng thuật toán', 'Đề cập đến distributed rate limiting với Redis'],
  },
  {
    content: 'Connection pooling là gì? Tại sao quan trọng và cách config pool size tối ưu?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    tags: ['connection pool', 'database', 'performance', 'backend'],
    expectedDuration: 90,
    sampleAnswer: 'Pool giữ sẵn N connections để tái sử dụng, tránh overhead tạo connection mới. Pool size tối ưu phụ thuộc vào: số CPU, query duration, concurrency. Formula: pool_size = (core_count * 2) + effective_spindle_count.',
    hints: ['Giải thích overhead của việc tạo DB connection', 'Đề cập đến connection timeout, idle timeout'],
  },
  {
    content: 'Giải thích microservices architecture. Ưu nhược điểm so với monolithic và khi nào nên migrate?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Architecture',
    tags: ['microservices', 'monolith', 'architecture', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Microservices: independent deploy, scale riêng từng service, polyglot. Nhược: distributed system complexity, network latency, eventual consistency. Monolith: đơn giản hơn khi team nhỏ. Migrate khi team lớn, domain rõ ràng.',
    hints: ['Đề cập đến service discovery, API gateway', 'Nêu Domain-Driven Design trong context microservices'],
  },
  {
    content: 'OAuth 2.0 flow hoạt động như thế nào? Giải thích Authorization Code Flow và khi nào dùng các grant types khác.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Authentication',
    tags: ['oauth', 'security', 'auth', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Authorization Code: FE redirect → provider → callback với code → BE đổi code lấy token. Client Credentials: service-to-service. Device Code: TV/IoT. PKCE: cho public clients (SPA, mobile).',
    hints: ['Giải thích tại sao code flow an toàn hơn implicit', 'Đề cập đến PKCE'],
  },
  {
    content: 'Làm thế nào để handle database migration an toàn trên production không downtime?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Database',
    tags: ['migration', 'database', 'deployment', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Expand-contract pattern: thêm column mới → deploy code hỗ trợ cả 2 → backfill data → remove column cũ. Tránh rename/drop trực tiếp. Feature flags để kiểm soát rollout. Blue-green deployment.',
    hints: ['Đề cập đến backward compatibility', 'Nêu ví dụ với rename column'],
  },
  {
    content: 'Giải thích các HTTP status codes phổ biến. Sự khác biệt giữa 401 vs 403, 400 vs 422, 503 vs 504.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'HTTP',
    tags: ['http', 'status code', 'rest', 'backend'],
    expectedDuration: 90,
    sampleAnswer: '401 Unauthorized: chưa xác thực. 403 Forbidden: đã xác thực nhưng không có quyền. 400 Bad Request: syntax sai. 422 Unprocessable Entity: syntax đúng nhưng semantic sai. 503 Service Unavailable. 504 Gateway Timeout.',
    hints: ['Phân nhóm 2xx, 3xx, 4xx, 5xx', 'Nêu context sử dụng đúng trong API design'],
  },

  // ─────────────────────────────────────────
  // SYSTEM DESIGN (20)
  // ─────────────────────────────────────────
  {
    content: 'Thiết kế hệ thống rút ngắn URL (URL Shortener) như bit.ly. Xử lý 100M URLs và 10B redirects/tháng.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'url shortener', 'hashing', 'database'],
    expectedDuration: 1800,
    sampleAnswer: 'Clarify requirements → Estimation → High-level design: API, DB schema. Hash function (Base62, 7 chars = 62^7 = 3.5T). DB: Write path (generate + store), Read path (cache-heavy). Redis cache 20% hot URLs. CDN cho redirect.',
    hints: ['Bắt đầu bằng clarify requirements và estimation', 'Thảo luận về hash collision handling'],
  },
  {
    content: 'Thiết kế hệ thống chat real-time như Messenger. Hỗ trợ 1-1 và group chat, online presence.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'chat', 'websocket', 'real-time'],
    expectedDuration: 1800,
    sampleAnswer: 'WebSocket cho persistent connection. Chat service, Presence service riêng. Message storage: Cassandra (high write throughput). Media: S3. Fan-out: cho group chat dùng message queue. End-to-end encryption.',
    hints: ['Phân biệt 1-1 vs group chat fan-out strategy', 'Đề cập đến offline message delivery'],
  },
  {
    content: 'Thiết kế hệ thống newsfeed của mạng xã hội (như Facebook). Hỗ trợ 1B users, 1M posts/ngày.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'newsfeed', 'fan-out', 'social media'],
    expectedDuration: 1800,
    sampleAnswer: 'Fan-out on write (push model) cho users bình thường. Fan-out on read (pull model) cho celebrities (nhiều followers). Hybrid approach. Redis sorted set cho feed. Ranking service. Pagination với cursor.',
    hints: ['Thảo luận trade-off giữa push vs pull model', 'Đề cập đến celebrity problem'],
  },
  {
    content: 'Thiết kế hệ thống notification. Hỗ trợ push notification, email, SMS cho 100M users.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'notification', 'push', 'email', 'queue'],
    expectedDuration: 1800,
    sampleAnswer: 'Notification service nhận event → Message Queue (phân loại theo channel) → Workers (email/push/SMS). Rate limiting per user. Template engine. Retry mechanism. User preference (do not disturb). Analytics tracking.',
    hints: ['Đề cập đến delivery guarantee (at-least-once, exactly-once)', 'Thảo luận về priority queue'],
  },
  {
    content: 'Thiết kế hệ thống lưu trữ file như Dropbox/Google Drive. Upload/download file lớn, sync across devices.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'storage', 'file upload', 's3'],
    expectedDuration: 1800,
    sampleAnswer: 'Chunk file thành 4MB blocks, dedup bằng hash. Upload: presigned URL lên S3 trực tiếp. Metadata service (DB). Sync service với delta sync. CDN cho download. Versioning. Conflict resolution.',
    hints: ['Giải thích chunking và deduplication', 'Đề cập đến delta sync để giảm bandwidth'],
  },
  {
    content: 'Thiết kế hệ thống search autocomplete (typeahead). Mỗi ký tự gõ trả về 5 gợi ý trong < 100ms.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'search', 'trie', 'autocomplete'],
    expectedDuration: 1800,
    sampleAnswer: 'Trie data structure hoặc prefix hash. Offline job tính tần suất từ search logs. Cache hot prefixes. Trie sharding theo prefix. Trie serialization. Personalization layer nếu cần.',
    hints: ['So sánh Trie vs Elasticsearch', 'Đề cập đến cách update Trie mà không downtime'],
  },
  {
    content: 'Thiết kế hệ thống thanh toán (Payment System). Đảm bảo exactly-once processing, idempotency.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'payment', 'idempotency', 'transaction'],
    expectedDuration: 1800,
    sampleAnswer: 'Idempotency key cho mỗi transaction. Double-entry bookkeeping. Distributed transaction (2PC hoặc Saga pattern). Reconciliation job. PCI DSS compliance. Retry với exponential backoff. Immutable event log.',
    hints: ['Tại sao idempotency quan trọng', 'Giải thích Saga pattern để tránh distributed transaction'],
  },
  {
    content: 'Thiết kế hệ thống streaming video như YouTube. Upload, transcode, deliver video đến hàng triệu users.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'video', 'streaming', 'cdn', 'transcoding'],
    expectedDuration: 1800,
    sampleAnswer: 'Upload: chunked upload → S3. Transcoding pipeline (queue + workers) → nhiều resolution. Storage: S3 cho original, CDN edge servers cho delivery. Adaptive bitrate streaming (HLS/DASH). Metadata DB.',
    hints: ['Đề cập đến adaptive bitrate streaming', 'Thảo luận về CDN cache strategy cho video'],
  },
  {
    content: 'Thiết kế Rate Limiter cho API Gateway. Hỗ trợ nhiều thuật toán, distributed system.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'rate limiter', 'redis', 'algorithm'],
    expectedDuration: 1800,
    sampleAnswer: 'Rules engine (lấy từ DB/cache). Redis cho distributed counter. Algorithms: Token Bucket (default), Sliding Window Log, Fixed Window Counter. Header trả về remaining/reset. Soft vs hard limit. Race condition với Lua script.',
    hints: ['Giải thích race condition trong distributed rate limiter', 'Đề cập đến Redis Lua script để atomic operations'],
  },
  {
    content: 'Thiết kế hệ thống distributed cache. So sánh với Redis và khi nào tự build vs dùng off-the-shelf.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'cache', 'distributed', 'redis'],
    expectedDuration: 1800,
    sampleAnswer: 'Consistent hashing để distribute keys. Replication cho availability. Eviction policies (LRU, LFU). Cache coherence problem. Write-through vs write-behind. Hot key problem. Thundering herd protection.',
    hints: ['Giải thích consistent hashing và virtual nodes', 'Thảo luận về hot key problem và solutions'],
  },
  {
    content: 'Thiết kế hệ thống recommendation cho e-commerce. Gợi ý sản phẩm dựa trên lịch sử user.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'recommendation', 'ml', 'collaborative filtering'],
    expectedDuration: 1800,
    sampleAnswer: 'Collaborative filtering (user-based, item-based). Content-based filtering. Hybrid approach. Offline training (Spark). Online serving (feature store, model server). A/B testing framework. Cold start problem cho new users.',
    hints: ['Giải thích cold start problem', 'Đề cập đến online vs offline model serving'],
  },
  {
    content: 'Thiết kế real-time leaderboard cho game. Cập nhật score liên tục, query top 10 trong < 10ms.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'leaderboard', 'redis', 'sorted set'],
    expectedDuration: 1800,
    sampleAnswer: 'Redis Sorted Set: ZADD O(log N), ZRANGE O(log N + K). Shard theo game room hoặc time window. Periodic snapshot sang DB. Global leaderboard: merge top-K từ shards. Rank cho user cụ thể: ZRANK.',
    hints: ['Tại sao Redis Sorted Set phù hợp', 'Thảo luận về global vs local leaderboard'],
  },
  {
    content: 'Thiết kế hệ thống logging và monitoring tập trung cho microservices. ELK stack.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'logging', 'monitoring', 'elk', 'observability'],
    expectedDuration: 1800,
    sampleAnswer: 'Log collection (Filebeat/Fluentd) → Kafka → Logstash → Elasticsearch → Kibana. Structured logging (JSON). Correlation ID cho distributed tracing. Metrics (Prometheus + Grafana). Alerting rules. Log retention policy.',
    hints: ['Giải thích 3 pillars of observability: logs, metrics, traces', 'Đề cập đến sampling cho high-traffic'],
  },
  {
    content: 'Thiết kế API Gateway. Xử lý authentication, routing, load balancing, circuit breaker.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'api gateway', 'load balancer', 'circuit breaker'],
    expectedDuration: 1800,
    sampleAnswer: 'Auth middleware (JWT verify). Dynamic routing table. Load balancing (round robin, least connections, weighted). Circuit breaker (Closed/Open/Half-Open). Rate limiting. Request/response transformation. Service discovery integration.',
    hints: ['Giải thích circuit breaker pattern', 'Đề cập đến service mesh vs API gateway'],
  },
  {
    content: 'Thiết kế ứng dụng đặt xe như Grab/Uber. Matching driver-rider, real-time location tracking.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'uber', 'geospatial', 'matching', 'real-time'],
    expectedDuration: 1800,
    sampleAnswer: 'Location service: driver cập nhật vị trí mỗi 5s (WebSocket). Geospatial index (Quadtree, Geohash). Matching service: tìm driver gần nhất → ETA calculation. Surge pricing. Trip lifecycle state machine.',
    hints: ['Giải thích Geohash và Quadtree', 'Thảo luận về matching algorithm trade-offs'],
  },
  {
    content: 'Thiết kế hệ thống đặt phòng khách sạn như Booking.com. Tránh double-booking, giá động.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'booking', 'concurrency', 'inventory'],
    expectedDuration: 1800,
    sampleAnswer: 'Inventory service với optimistic locking. Reserve → Checkout flow với timeout. Idempotent booking. Search: Elasticsearch với availability filter. Pricing service (rule-based + demand). Distributed lock với Redis cho peak time.',
    hints: ['Giải thích optimistic vs pessimistic locking', 'Đề cập đến overbooking strategy'],
  },
  {
    content: 'Thiết kế hệ thống CDN (Content Delivery Network). Cách cache và invalidate content.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'cdn', 'cache', 'content delivery'],
    expectedDuration: 1800,
    sampleAnswer: 'Edge servers tại nhiều PoPs. Anycast routing. Cache hierarchy (L1 edge → L2 regional → origin). Cache key design. TTL-based invalidation. Purge API. Cache miss: request to origin, cache the response. HTTPS termination at edge.',
    hints: ['Giải thích Anycast và BGP routing', 'Thảo luận về cache key design'],
  },
  {
    content: 'Thiết kế hệ thống CI/CD pipeline. Từ code commit đến production deployment không downtime.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    tags: ['system design', 'cicd', 'deployment', 'devops'],
    expectedDuration: 1800,
    sampleAnswer: 'Trigger: git push → Build (Docker image) → Test (unit, integration, e2e) → Security scan → Staging deploy → Smoke test → Blue-green production deploy → Health check → Auto-rollback on failure. Feature flags.',
    hints: ['Giải thích blue-green vs canary deployment', 'Đề cập đến rollback strategy'],
  },
  {
    content: 'Thiết kế hệ thống distributed search engine như Elasticsearch. Indexing, sharding, replication.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'search engine', 'elasticsearch', 'inverted index'],
    expectedDuration: 1800,
    sampleAnswer: 'Inverted index: term → list of document IDs. Sharding theo document ID (routing). Replication (primary + replicas). Index lifecycle management. Relevance scoring (TF-IDF, BM25). Near real-time indexing. Bulk API.',
    hints: ['Giải thích inverted index', 'Thảo luận về index vs query time relevance tuning'],
  },
  {
    content: 'Thiết kế hệ thống web crawler. Crawl 1B trang web, xử lý duplicate, robots.txt.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    tags: ['system design', 'crawler', 'distributed', 'bfs'],
    expectedDuration: 1800,
    sampleAnswer: 'Seed URLs → Priority Queue (politeness, freshness) → Fetcher workers → Content parser → URL extractor → Dedup (Bloom filter) → Storage (S3). DNS cache. Rate limiting per domain. robots.txt compliance. Checksum dedup.',
    hints: ['Giải thích Bloom filter cho URL deduplication', 'Thảo luận về politeness và crawl rate limiting'],
  },

  // ─────────────────────────────────────────
  // CODING (20)
  // ─────────────────────────────────────────
  {
    content: 'Viết function đảo ngược một chuỗi string mà không dùng method reverse() có sẵn.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['string', 'algorithm', 'coding', 'easy'],
    expectedDuration: 300,
    sampleAnswer: 'function reverse(s) { let r = ""; for (let i = s.length - 1; i >= 0; i--) r += s[i]; return r; } // hoặc dùng two-pointer. Time: O(n), Space: O(n)',
    hints: ['Two-pointer approach', 'Xem xét Unicode characters (emoji, surrogate pairs)'],
  },
  {
    content: 'Viết function kiểm tra một chuỗi có phải palindrome không (đọc xuôi ngược giống nhau). Bỏ qua spaces và chữ hoa/thường.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['string', 'two pointer', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Normalize: lowercase + remove non-alphanumeric. Two-pointer: left và right so sánh từ 2 đầu. Time: O(n), Space: O(1) với two-pointer.',
    hints: ['Clean input trước khi check', 'Two-pointer O(1) space vs reverse O(n) space'],
  },
  {
    content: 'Giải bài Two Sum: cho mảng số nguyên và target, trả về indices của 2 số cộng lại bằng target.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['array', 'hash map', 'coding', 'leetcode'],
    expectedDuration: 300,
    sampleAnswer: 'Brute force O(n²). Tối ưu: dùng HashMap. Duyệt mảng, với mỗi num check xem (target - num) có trong map không. Nếu có, return indices. Nếu không, add num vào map. Time: O(n), Space: O(n).',
    hints: ['HashMap key là value, value là index', 'Xử lý trường hợp duplicate numbers'],
  },
  {
    content: 'Implement Fizz Buzz: in số từ 1-100, chia hết cho 3 in "Fizz", chia hết cho 5 in "Buzz", cả hai in "FizzBuzz".',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['basic', 'modulo', 'coding'],
    expectedDuration: 180,
    sampleAnswer: 'for (let i = 1; i <= 100; i++) { let out = ""; if (i % 3 === 0) out += "Fizz"; if (i % 5 === 0) out += "Buzz"; console.log(out || i); } // Tránh if-else lồng nhau',
    hints: ['Xử lý FizzBuzz trước để tránh logic lỗi', 'Có thể dùng array lookup thay if-else'],
  },
  {
    content: 'Implement binary search trên mảng đã sắp xếp. Return index của phần tử cần tìm, -1 nếu không có.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['array', 'binary search', 'algorithm', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'left = 0, right = arr.length - 1. mid = Math.floor((left + right) / 2). So sánh arr[mid] với target. Narrow range. Loop until left > right. Time: O(log n), Space: O(1).',
    hints: ['Tránh integer overflow: mid = left + (right - left) / 2', 'Phân biệt lower/upper bound variant'],
  },
  {
    content: 'Tìm tất cả các phần tử bị lặp trong một mảng. Trả về array của các duplicates.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['array', 'hash set', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Dùng Set để track seen. Dùng Set khác cho duplicates (tránh add 3 lần). Trả về Array.from(duplicates). Time: O(n), Space: O(n).',
    hints: ['Dùng 2 Set để track seen và duplicates riêng', 'Xem xét yêu cầu về thứ tự kết quả'],
  },
  {
    content: 'Implement function deep clone một object (không dùng JSON.parse/stringify). Xử lý circular reference.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Coding',
    tags: ['object', 'recursion', 'coding', 'advanced'],
    expectedDuration: 600,
    sampleAnswer: 'Dùng WeakMap để track visited objects (xử lý circular). Recursive: với mỗi property, nếu primitive thì copy, nếu object/array thì recurse. Xử lý Date, RegExp, Map, Set riêng.',
    hints: ['WeakMap cho circular reference', 'Handle special types: Date, RegExp, Map, Set'],
  },
  {
    content: 'Implement function debounce: trì hoãn thực thi function cho đến khi không còn được gọi trong X ms.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['function', 'closure', 'coding', 'frontend'],
    expectedDuration: 300,
    sampleAnswer: 'function debounce(fn, delay) { let timer; return function(...args) { clearTimeout(timer); timer = setTimeout(() => fn.apply(this, args), delay); }; } // Dùng closure để giữ timer reference.',
    hints: ['Closure để giữ timer', 'Xem xét trailing vs leading edge option'],
  },
  {
    content: 'Implement function throttle: đảm bảo function chỉ được gọi tối đa 1 lần trong mỗi X ms.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['function', 'closure', 'coding', 'frontend'],
    expectedDuration: 300,
    sampleAnswer: 'Dùng timestamp của lần gọi cuối. Nếu elapsed < delay, bỏ qua. Nếu elapsed >= delay, thực thi và cập nhật lastTime. Hoặc dùng flag isThrottled.',
    hints: ['So sánh throttle vs debounce', 'Timestamp approach vs flag approach'],
  },
  {
    content: 'Flatten một mảng lồng nhau bất kỳ độ sâu: [[1,[2,[3]]],4] → [1,2,3,4]. Không dùng Array.flat().',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['array', 'recursion', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Recursive: duyệt từng element, nếu array thì recurse, nếu không thì push vào result. Hoặc iterative với stack. Time: O(n) với n là tổng số elements.',
    hints: ['Recursive vs iterative approach', 'Stack-based iterative tránh stack overflow cho mảng rất sâu'],
  },
  {
    content: 'Kiểm tra dấu ngoặc cân bằng: "((){}[])" → true, "([)]" → false. Xử lý {, }, (, ), [, ].',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['stack', 'string', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Dùng Stack. Khi gặp mở ngoặc, push. Khi gặp đóng ngoặc, pop và check match. Cuối cùng stack phải rỗng. Time: O(n), Space: O(n).',
    hints: ['HashMap để map closing → opening bracket', 'Edge cases: empty string, chỉ có mở hoặc đóng ngoặc'],
  },
  {
    content: 'Tìm số bị thiếu trong mảng [1..n] với n-1 phần tử, không có duplicate. Ví dụ: [1,2,4,5] → 3.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['array', 'math', 'coding'],
    expectedDuration: 240,
    sampleAnswer: 'Cách 1: Sum formula. Expected = n*(n+1)/2. Actual = sum(arr). Missing = Expected - Actual. Time: O(n), Space: O(1). Cách 2: XOR approach cũng O(1) space.',
    hints: ['Math formula O(1) space', 'XOR approach: a XOR a = 0'],
  },
  {
    content: 'Group các anagram lại với nhau: ["eat","tea","tan","ate","nat","bat"] → [["eat","tea","ate"],["tan","nat"],["bat"]].',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['string', 'hash map', 'sorting', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Sort từng string làm key của HashMap. Ví dụ "eat" → "aet", "tea" → "aet" → cùng group. Time: O(n * k log k) với k là max string length.',
    hints: ['Sorted string làm key', 'Hoặc dùng character frequency count làm key'],
  },
  {
    content: 'Implement LRU Cache với O(1) cho cả get và put. Sử dụng capacity cố định.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Coding',
    tags: ['data structure', 'lru', 'linked list', 'hash map', 'coding'],
    expectedDuration: 600,
    sampleAnswer: 'HashMap + Doubly Linked List. HashMap: key → node. DLL: maintain order (head = most recent, tail = least recent). Get: move node to head. Put: add to head, evict tail nếu over capacity. O(1) cả hai.',
    hints: ['Tại sao cần Doubly Linked List', 'Dummy head/tail nodes để đơn giản hóa code'],
  },
  {
    content: 'Tìm longest substring không có ký tự lặp lại. "abcabcbb" → 3 ("abc").',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['string', 'sliding window', 'hash map', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Sliding window + HashMap (char → last index). Mở rộng right, nếu char đã seen, co lại left đến sau index đó. Cập nhật max length. Time: O(n), Space: O(min(m,n)) với m là alphabet size.',
    hints: ['Sliding window technique', 'left = Math.max(left, map.get(char) + 1) để xử lý đúng'],
  },
  {
    content: 'Dịch chuyển tất cả số 0 về cuối mảng mà không thay đổi thứ tự các phần tử khác. In-place.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Coding',
    tags: ['array', 'two pointer', 'in-place', 'coding'],
    expectedDuration: 240,
    sampleAnswer: 'Two-pointer: insertPos = 0. Duyệt mảng, nếu element != 0, đặt vào arr[insertPos++]. Sau đó fill phần còn lại bằng 0. Time: O(n), Space: O(1).',
    hints: ['Two-pointer in-place', 'Tránh unnecessary swaps'],
  },
  {
    content: 'Implement function curry: biến f(a,b,c) thành f(a)(b)(c). Hỗ trợ cả f(a,b)(c) và f(a)(b,c).',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Coding',
    tags: ['function', 'closure', 'functional programming', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'function curry(fn) { return function curried(...args) { if (args.length >= fn.length) return fn(...args); return (...more) => curried(...args, ...more); }; } // Dùng fn.length để biết arity.',
    hints: ['fn.length cho biết số tham số', 'Accumulate args qua nhiều lần gọi'],
  },
  {
    content: 'Tìm Maximum Subarray sum (Kadane\'s Algorithm). [-2,1,-3,4,-1,2,1,-5,4] → 6 ([4,-1,2,1]).',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['array', 'dynamic programming', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'Kadane: currentSum = Math.max(num, currentSum + num). maxSum = Math.max(maxSum, currentSum). Nếu currentSum âm, reset bằng cách lấy num. Time: O(n), Space: O(1).',
    hints: ['Tại sao reset khi currentSum âm', 'Xử lý trường hợp tất cả số âm'],
  },
  {
    content: 'Implement Promise.all từ đầu. Resolve khi tất cả resolve, reject ngay khi 1 reject.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Coding',
    tags: ['promise', 'async', 'javascript', 'coding'],
    expectedDuration: 600,
    sampleAnswer: 'return new Promise((resolve, reject) => { const results = []; let count = 0; promises.forEach((p, i) => Promise.resolve(p).then(val => { results[i] = val; if (++count === promises.length) resolve(results); }).catch(reject)); });',
    hints: ['Dùng index để giữ thứ tự kết quả', 'Xử lý empty array edge case'],
  },
  {
    content: 'Viết function memoize: cache kết quả của function dựa trên arguments để tránh tính toán lại.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Coding',
    tags: ['function', 'cache', 'closure', 'optimization', 'coding'],
    expectedDuration: 300,
    sampleAnswer: 'function memoize(fn) { const cache = new Map(); return function(...args) { const key = JSON.stringify(args); if (cache.has(key)) return cache.get(key); const result = fn.apply(this, args); cache.set(key, result); return result; }; }',
    hints: ['JSON.stringify làm cache key (lưu ý với objects)', 'WeakMap nếu args là objects để tránh memory leak'],
  },

  // ─────────────────────────────────────────
  // HR (10)
  // ─────────────────────────────────────────
  {
    content: 'Hãy giới thiệu bản thân bạn. (Tell me about yourself)',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Introduction',
    tags: ['introduction', 'hr', 'background'],
    expectedDuration: 120,
    sampleAnswer: 'Cấu trúc: Hiện tại (vai trò, skills) → Quá khứ (kinh nghiệm nổi bật) → Tương lai (tại sao bạn ở đây). Ngắn gọn 2-3 phút, tập trung vào khía cạnh liên quan đến vị trí ứng tuyển.',
    hints: ['Present → Past → Future formula', 'Tùy chỉnh câu trả lời theo job description'],
  },
  {
    content: 'Tại sao bạn muốn làm việc tại công ty chúng tôi? (Why do you want to work here?)',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Company Research',
    tags: ['motivation', 'company research', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Research company trước: sản phẩm, culture, tech stack, mission. Kết nối với career goals của bạn. Tránh nói chỉ vì lương hay địa điểm. Thể hiện genuine interest.',
    hints: ['Research company kỹ trước interview', 'Kết nối culture/mission với values cá nhân'],
  },
  {
    content: 'Điểm mạnh lớn nhất của bạn là gì liên quan đến vị trí Software Engineer này?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Self Assessment',
    tags: ['strengths', 'self-awareness', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Chọn 2-3 điểm mạnh liên quan đến job. Back up bằng ví dụ cụ thể. Tránh generic ("tôi chăm chỉ"). Ví dụ tốt: "Tôi có khả năng debug phức tạp, cụ thể..."',
    hints: ['Liên kết strengths với requirements của job', 'Dùng ví dụ cụ thể thay vì nói chung chung'],
  },
  {
    content: 'Điểm yếu của bạn là gì? Bạn đang làm gì để cải thiện?',
    category: 'hr',
    difficulty: 'medium',
    topic: 'Self Assessment',
    tags: ['weakness', 'self-awareness', 'improvement', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Chọn điểm yếu thật nhưng không ảnh hưởng critical đến job. Quan trọng nhất: nêu action plan cụ thể bạn đang làm để improve. Tránh nói "tôi làm việc quá chăm chỉ".',
    hints: ['Phải là điểm yếu thật, có đang cải thiện', 'Tránh điểm yếu là core skill của job'],
  },
  {
    content: 'Trong 3-5 năm tới, bạn thấy mình đang ở đâu trong sự nghiệp?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Career Goals',
    tags: ['career goals', 'ambition', 'planning', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả growth path realistic: master current role → expand responsibilities → leadership nếu phù hợp. Kết nối với cơ hội phát triển tại công ty. Tránh nói "tôi muốn ngồi ở vị trí của bạn".',
    hints: ['Align với growth opportunities tại company', 'Thể hiện ambition nhưng realistic'],
  },
  {
    content: 'Tại sao bạn muốn rời công ty hiện tại? (Why are you leaving your current job?)',
    category: 'hr',
    difficulty: 'medium',
    topic: 'Career Transition',
    tags: ['leaving', 'motivation', 'honesty', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Giữ thái độ chuyên nghiệp, không nói xấu công ty cũ. Focus vào pull factors (muốn học thêm, cơ hội mới) hơn push factors (không thích sếp cũ). Thành thật nhưng diplomatic.',
    hints: ['Không nói xấu công ty/sếp cũ', 'Focus vào cơ hội mới thay vì vấn đề cũ'],
  },
  {
    content: 'Mức lương mong muốn của bạn là bao nhiêu?',
    category: 'hr',
    difficulty: 'medium',
    topic: 'Salary Negotiation',
    tags: ['salary', 'negotiation', 'hr'],
    expectedDuration: 60,
    sampleAnswer: 'Research market rate trước. Đưa ra range dựa trên research, experience, skills. Tránh đưa con số đầu tiên nếu có thể. Đề cập đến total compensation (base, bonus, equity, benefits).',
    hints: ['Research Glassdoor, ITviec, LinkedIn Salary', 'Đưa range thay vì con số cụ thể'],
  },
  {
    content: 'Bạn xử lý stress và áp lực trong công việc như thế nào?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Stress Management',
    tags: ['stress', 'work-life balance', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả cơ chế coping cụ thể: breakdown tasks, prioritize, giao tiếp khi overwhelmed, work-life balance habits. Nêu ví dụ cụ thể bạn đã handle stress hiệu quả.',
    hints: ['Thể hiện self-awareness về stress triggers', 'Nêu healthy coping mechanisms'],
  },
  {
    content: 'Điều gì khiến bạn là ứng viên tốt nhất cho vị trí này?',
    category: 'hr',
    difficulty: 'medium',
    topic: 'Value Proposition',
    tags: ['value', 'pitch', 'confidence', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Tóm tắt 3 điểm mạnh phù hợp nhất với job requirements. Kết nối kinh nghiệm với pain points của company. Thể hiện enthusiasm và fit với culture. Kết thúc bằng cam kết đóng góp.',
    hints: ['Kết nối skills với specific job requirements', 'Thể hiện culture fit, không chỉ technical skills'],
  },
  {
    content: 'Bạn có câu hỏi nào cho chúng tôi không? (Do you have any questions for us?)',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Interview Closing',
    tags: ['questions', 'curiosity', 'engagement', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Luôn hỏi! Ví dụ hay: "Tech stack và architecture hiện tại?", "Team culture như thế nào?", "Thách thức lớn nhất của team hiện tại?", "Cơ hội learning và growth?", "Quy trình onboarding?". Tránh hỏi về lương, benefits ở vòng đầu.',
    hints: ['Chuẩn bị 3-5 câu hỏi', 'Hỏi về tech, team, growth thay vì chỉ benefits'],
  },
];

const seedQuestions = async () => {
  try {
    const count = await Question.countDocuments();
    if (count > 0) {
      console.log(`[Seeder] Questions already seeded (${count} records). Skipping.`);
      return;
    }

    await Question.insertMany(questions);
    console.log(`[Seeder] Seeded ${questions.length} questions successfully.`);
  } catch (err) {
    console.error('[Seeder] Failed to seed questions:', err.message);
  }
};

module.exports = seedQuestions;
