const Question = require('../models/question.model');

const questions = [
  // ─────────────────────────────────────────
  // BEHAVIORAL (20) — role: General
  // ─────────────────────────────────────────
  {
    content: 'Hãy kể về một lần bạn phải làm việc dưới áp lực lớn. Bạn đã xử lý tình huống đó như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Pressure & Stress',
    role: 'General',
    level: 'junior',
    tags: ['pressure', 'stress management', 'problem solving'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả tình huống cụ thể, áp lực đến từ đâu (deadline, yêu cầu thay đổi...). Giải thích cách bạn ưu tiên công việc, giao tiếp với team, và kết quả đạt được.',
    hints: ['Dùng phương pháp STAR (Situation, Task, Action, Result)', 'Nêu rõ kết quả cụ thể'],
  },
  {
    content: 'Kể về một lần bạn thất bại trong dự án. Bạn đã học được gì từ đó?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Learning from Failure',
    role: 'General',
    level: 'junior',
    tags: ['failure', 'growth mindset', 'self-awareness'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả thất bại một cách trung thực, không đổ lỗi cho người khác. Tập trung vào bài học rút ra và những thay đổi bạn thực hiện sau đó.',
    hints: ['Chọn thất bại thực sự có ý nghĩa, không quá nhỏ nhặt', 'Nhấn mạnh vào hành động cải thiện'],
  },
  {
    content: 'Bạn xử lý xung đột với đồng nghiệp như thế nào? Hãy chia sẻ một ví dụ cụ thể.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Conflict Resolution',
    role: 'General',
    level: 'junior',
    tags: ['conflict', 'teamwork', 'communication'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả xung đột, cách bạn tiếp cận đồng nghiệp một cách bình tĩnh, lắng nghe quan điểm của họ, và tìm giải pháp chung.',
    hints: ['Thể hiện sự trưởng thành và kỹ năng lắng nghe', 'Không nói xấu đồng nghiệp'],
  },
  {
    content: 'Mô tả dự án khó khăn nhất bạn từng tham gia. Vai trò của bạn là gì và kết quả ra sao?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Project Experience',
    role: 'General',
    level: 'middle',
    tags: ['project', 'challenge', 'achievement'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả rõ dự án, thách thức cụ thể (technical debt, yêu cầu mơ hồ, deadline ngắn...), đóng góp cá nhân, và kết quả đo lường được.',
    hints: ['Chọn dự án có impact rõ ràng', 'Nêu metrics cụ thể nếu có'],
  },
  {
    content: 'Kể về một lần bạn thể hiện khả năng lãnh đạo, dù bạn không phải là manager.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Leadership',
    role: 'General',
    level: 'junior',
    tags: ['leadership', 'initiative', 'influence'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả tình huống bạn chủ động dẫn dắt nhóm, đưa ra hướng giải quyết, hoặc motivate đồng đội mà không cần chức danh.',
    hints: ['Leadership không cần chức danh', 'Tập trung vào hành động chủ động của bạn'],
  },
  {
    content: 'Khi có nhiều deadline cùng lúc, bạn sắp xếp ưu tiên công việc như thế nào?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Time Management',
    role: 'General',
    level: 'fresher',
    tags: ['prioritization', 'time management', 'organization'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến framework bạn dùng (Eisenhower Matrix, MoSCoW...), cách giao tiếp với stakeholders khi cần điều chỉnh deadline.',
    hints: ['Nêu phương pháp cụ thể', 'Đề cập đến việc giao tiếp khi quá tải'],
  },
  {
    content: 'Hãy kể về một lần bạn phải học một công nghệ mới trong thời gian ngắn. Bạn tiếp cận như thế nào?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Learning Agility',
    role: 'General',
    level: 'fresher',
    tags: ['learning', 'adaptability', 'self-improvement'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả cách bạn xác định kiến thức cần thiết, nguồn tài liệu bạn dùng, cách bạn thực hành và áp dụng nhanh vào dự án.',
    hints: ['Thể hiện tính chủ động trong học tập', 'Đề cập đến cách bạn xử lý khi gặp khó khăn'],
  },
  {
    content: 'Kể về một lần bạn không đồng ý với quyết định của manager. Bạn xử lý thế nào?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Upward Management',
    role: 'General',
    level: 'middle',
    tags: ['communication', 'disagreement', 'professionalism'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn trình bày quan điểm dựa trên data/logic, lắng nghe lý do của manager, và chấp nhận hoặc thuyết phục một cách chuyên nghiệp.',
    hints: ['Tránh tỏ ra bướng bỉnh', 'Thể hiện tư duy phản biện có xây dựng'],
  },
  {
    content: 'Bạn phản ứng như thế nào khi nhận được feedback tiêu cực về code của mình?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Receiving Feedback',
    role: 'General',
    level: 'fresher',
    tags: ['feedback', 'growth', 'ego'],
    expectedDuration: 90,
    sampleAnswer: 'Thể hiện sự cởi mở với feedback, đặt câu hỏi để hiểu rõ, và mô tả cách bạn cải thiện dựa trên feedback đó.',
    hints: ['Tách cái tôi khỏi code', 'Feedback là cơ hội học tập'],
  },
  {
    content: 'Hãy kể về một lần bạn giúp đỡ đồng nghiệp vượt qua khó khăn kỹ thuật.',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Collaboration',
    role: 'General',
    level: 'fresher',
    tags: ['helping', 'teamwork', 'knowledge sharing'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả vấn đề đồng nghiệp gặp phải, cách bạn tiếp cận để giải thích/hỗ trợ, và kết quả của sự hợp tác đó.',
    hints: ['Thể hiện kỹ năng giải thích và kiên nhẫn', 'Nêu impact của sự giúp đỡ'],
  },
  {
    content: 'Thành tựu kỹ thuật lớn nhất của bạn cho đến nay là gì?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Achievement',
    role: 'General',
    level: 'junior',
    tags: ['achievement', 'pride', 'impact'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả thành tựu với context rõ ràng, đóng góp cá nhân, và impact đo lường được (tăng performance X%, giảm bug Y%).',
    hints: ['Dùng số liệu cụ thể nếu có', 'Giải thích tại sao bạn tự hào về điều này'],
  },
  {
    content: 'Khi nhận yêu cầu mơ hồ từ khách hàng, bạn làm gì để làm rõ trước khi bắt tay vào code?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Requirement Clarification',
    role: 'General',
    level: 'junior',
    tags: ['communication', 'requirements', 'proactive'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến việc đặt câu hỏi làm rõ, viết document tóm tắt hiểu biết, xác nhận lại với stakeholder trước khi bắt đầu.',
    hints: ['Thể hiện tính proactive', 'Đề cập đến risk của việc không làm rõ'],
  },
  {
    content: 'Kể về một lần bạn vô tình gây ra bug trên production. Bạn xử lý tình huống đó như thế nào?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Incident Handling',
    role: 'General',
    level: 'middle',
    tags: ['bug', 'production', 'responsibility', 'crisis'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả incident, cách bạn nhận trách nhiệm, các bước bạn thực hiện để hotfix, và cách ngăn tái phát (post-mortem, tests...).',
    hints: ['Không giấu hay đổ lỗi', 'Tập trung vào quy trình xử lý và phòng ngừa'],
  },
  {
    content: 'Hãy kể về một lần bạn cải thiện quy trình làm việc của team.',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Process Improvement',
    role: 'General',
    level: 'junior',
    tags: ['process', 'efficiency', 'initiative'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả vấn đề trong quy trình hiện tại, đề xuất bạn đưa ra, cách bạn thuyết phục team, và kết quả sau khi thực hiện.',
    hints: ['Thể hiện tư duy cải tiến liên tục', 'Dùng số liệu trước và sau'],
  },
  {
    content: 'Mô tả cách bạn xử lý một stakeholder khó tính hoặc thường xuyên thay đổi yêu cầu.',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Stakeholder Management',
    role: 'General',
    level: 'middle',
    tags: ['stakeholder', 'communication', 'professionalism'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn thiết lập expectations, document các thay đổi, và maintain mối quan hệ chuyên nghiệp dù có áp lực.',
    hints: ['Không nói xấu stakeholder', 'Thể hiện kỹ năng đàm phán và giao tiếp'],
  },
  {
    content: 'Kể về một quyết định khó khăn bạn phải đưa ra trong dự án. Bạn cân nhắc những yếu tố gì?',
    category: 'behavioral',
    difficulty: 'hard',
    topic: 'Decision Making',
    role: 'General',
    level: 'middle',
    tags: ['decision making', 'trade-offs', 'judgment'],
    expectedDuration: 150,
    sampleAnswer: 'Mô tả các lựa chọn, trade-offs kỹ thuật/business, cách bạn thu thập thông tin, và kết quả của quyết định đó.',
    hints: ['Thể hiện tư duy có cấu trúc', 'Đề cập đến các stakeholder liên quan'],
  },
  {
    content: 'Hãy kể về một lần bạn làm việc vượt mức yêu cầu để đảm bảo dự án thành công.',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Work Ethic',
    role: 'General',
    level: 'fresher',
    tags: ['dedication', 'ownership', 'going beyond'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả tình huống, lý do bạn chọn đi xa hơn, và impact của hành động đó lên team/dự án.',
    hints: ['Thể hiện ownership và trách nhiệm', 'Không quá đề cao bản thân'],
  },
  {
    content: 'Bạn duy trì động lực như thế nào khi làm những công việc lặp đi lặp lại hoặc nhàm chán?',
    category: 'behavioral',
    difficulty: 'easy',
    topic: 'Motivation',
    role: 'General',
    level: 'fresher',
    tags: ['motivation', 'attitude', 'consistency'],
    expectedDuration: 90,
    sampleAnswer: 'Đề cập đến việc tìm ý nghĩa trong công việc, tự đặt thử thách mới, hoặc kết nối công việc với mục tiêu lớn hơn.',
    hints: ['Thể hiện thái độ tích cực', 'Tránh nói bạn không bao giờ nhàm chán'],
  },
  {
    content: 'Kể về một lần công ty/team thay đổi hướng đột ngột. Bạn thích nghi như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Adaptability',
    role: 'General',
    level: 'junior',
    tags: ['change management', 'flexibility', 'adaptability'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả sự thay đổi, cảm xúc ban đầu, cách bạn điều chỉnh mindset, và những gì bạn làm để thích nghi nhanh chóng.',
    hints: ['Thể hiện tính linh hoạt', 'Đề cập đến cách bạn giúp người khác thích nghi'],
  },
  {
    content: 'Hãy kể về một lần bạn mentoring junior developer. Bạn tiếp cận như thế nào?',
    category: 'behavioral',
    difficulty: 'medium',
    topic: 'Mentoring',
    role: 'General',
    level: 'junior',
    tags: ['mentoring', 'teaching', 'leadership', 'patience'],
    expectedDuration: 120,
    sampleAnswer: 'Mô tả cách bạn assess trình độ của junior, xây dựng kế hoạch hướng dẫn, balance giữa cho câu trả lời và để họ tự tìm.',
    hints: ['Thể hiện sự kiên nhẫn và khả năng giải thích', 'Nêu kết quả phát triển của mentee'],
  },

  // ─────────────────────────────────────────
  // TECHNICAL — FRONTEND (15) — role: FE
  // ─────────────────────────────────────────
  {
    content: 'Virtual DOM là gì? Tại sao React sử dụng Virtual DOM và nó giúp cải thiện performance như thế nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    role: 'FE',
    level: 'junior',
    tags: ['react', 'virtual dom', 'performance', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Virtual DOM là bản sao nhẹ của Real DOM trong memory. React so sánh Virtual DOM mới và cũ (diffing), chỉ cập nhật phần thay đổi lên Real DOM (reconciliation), tránh re-render toàn bộ trang.',
    hints: ['Giải thích diffing algorithm', 'So sánh với Real DOM manipulation trực tiếp'],
  },
  {
    content: 'Giải thích sự khác biệt giữa useMemo và useCallback trong React. Khi nào nên dùng cái nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    role: 'FE',
    level: 'junior',
    tags: ['react', 'hooks', 'performance', 'memoization'],
    expectedDuration: 120,
    sampleAnswer: 'useMemo memoize giá trị tính toán, useCallback memoize function reference. Dùng useMemo khi có expensive computation, useCallback khi truyền callback xuống child component để tránh re-render không cần thiết.',
    hints: ['Nêu ví dụ cụ thể cho từng hook', 'Đề cập đến khi nào KHÔNG nên dùng (premature optimization)'],
  },
  {
    content: 'Event bubbling và event capturing trong JavaScript là gì? Sự khác biệt giữa stopPropagation và preventDefault?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    role: 'FE',
    level: 'junior',
    tags: ['javascript', 'events', 'dom', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Capturing: event đi từ root xuống target. Bubbling: event đi từ target lên root. stopPropagation ngừng lan truyền event, preventDefault ngăn hành vi mặc định của browser (submit form, follow link...).',
    hints: ['Vẽ sơ đồ nếu cần', 'Nêu ví dụ thực tế về event delegation'],
  },
  {
    content: 'Closure trong JavaScript là gì? Cho ví dụ thực tế về việc sử dụng closure.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    role: 'FE',
    level: 'junior',
    tags: ['javascript', 'closure', 'scope', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'Closure là function có thể truy cập variables từ outer scope sau khi outer function đã return. Ví dụ: counter function, module pattern, function factories.',
    hints: ['Giải thích lexical scope trước', 'Nêu ví dụ về closure trong vòng lặp (bug thường gặp)'],
  },
  {
    content: 'Giải thích Event Loop trong JavaScript. Tại sao JavaScript là single-threaded nhưng vẫn có thể xử lý async?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'JavaScript',
    role: 'FE',
    level: 'senior',
    tags: ['javascript', 'event loop', 'async', 'call stack'],
    expectedDuration: 150,
    sampleAnswer: 'Call Stack xử lý synchronous code. Web APIs xử lý async (setTimeout, fetch...). Callback Queue chứa các callback. Event Loop liên tục kiểm tra khi Call Stack rỗng sẽ push callback từ Queue vào Stack.',
    hints: ['Mô tả rõ Call Stack, Callback Queue, Microtask Queue', 'Giải thích tại sao Promise có priority cao hơn setTimeout'],
  },
  {
    content: 'So sánh Promise và async/await. Ưu nhược điểm của mỗi cách và khi nào nên dùng cái nào?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    role: 'FE',
    level: 'junior',
    tags: ['javascript', 'promise', 'async', 'await'],
    expectedDuration: 120,
    sampleAnswer: 'Promise: chain được, xử lý parallel tốt với Promise.all. async/await: code đọc dễ hơn, error handling với try/catch tự nhiên hơn. async/await build trên Promise, không loại trừ nhau.',
    hints: ['Đề cập đến Promise.all, Promise.race', 'Nêu cạm bẫy của async/await trong vòng lặp'],
  },
  {
    content: 'CSS Specificity hoạt động như thế nào? Giải thích thứ tự ưu tiên của các selector.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'CSS',
    role: 'FE',
    level: 'fresher',
    tags: ['css', 'specificity', 'selector', 'frontend'],
    expectedDuration: 90,
    sampleAnswer: 'Inline style (1,0,0,0) > ID (0,1,0,0) > Class/Pseudo-class/Attribute (0,0,1,0) > Element (0,0,0,1). !important override tất cả. Tính toán bằng cách cộng điểm từng loại selector.',
    hints: ['Dùng ví dụ số điểm cụ thể', 'Đề cập đến !important và tại sao nên tránh'],
  },
  {
    content: 'Sự khác biệt giữa SSR (Server-Side Rendering) và CSR (Client-Side Rendering)? Next.js giải quyết vấn đề gì?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Frontend Architecture',
    role: 'FE',
    level: 'junior',
    tags: ['ssr', 'csr', 'nextjs', 'performance', 'seo'],
    expectedDuration: 120,
    sampleAnswer: 'CSR: browser download JS rồi render, SEO kém, TTFB nhanh nhưng FCP chậm. SSR: server render HTML hoàn chỉnh, SEO tốt, FCP nhanh. Next.js hỗ trợ cả hai và thêm ISR, SSG.',
    hints: ['Đề cập đến SEO và performance metrics', 'Nêu trade-offs của từng approach'],
  },
  {
    content: 'CORS là gì? Tại sao browser chặn cross-origin request và cách xử lý CORS trong dự án thực tế?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Web Security',
    role: 'FE',
    level: 'junior',
    tags: ['cors', 'security', 'http', 'frontend', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'CORS là cơ chế bảo mật của browser ngăn request từ origin khác. Server cần set Access-Control-Allow-Origin header. Preflight request (OPTIONS) được gửi trước complex requests.',
    hints: ['Giải thích Same-Origin Policy', 'Đề cập đến simple vs preflight request'],
  },
  {
    content: 'Giải thích sự khác biệt giữa null, undefined và undeclared trong JavaScript.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'JavaScript',
    role: 'FE',
    level: 'fresher',
    tags: ['javascript', 'null', 'undefined', 'types'],
    expectedDuration: 90,
    sampleAnswer: 'undefined: variable được khai báo nhưng chưa gán giá trị. null: giá trị rỗng có chủ đích. undeclared: variable chưa được khai báo (gây ReferenceError). typeof null === "object" là bug của JS.',
    hints: ['Nêu ví dụ code cụ thể', 'Đề cập đến == vs === khi so sánh'],
  },
  {
    content: 'Webpack là gì và nó hoạt động như thế nào? Giải thích các khái niệm: entry, output, loader, plugin.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Build Tools',
    role: 'FE',
    level: 'junior',
    tags: ['webpack', 'bundler', 'build tools', 'frontend'],
    expectedDuration: 150,
    sampleAnswer: 'Webpack là module bundler. Entry: điểm bắt đầu. Output: file bundle đầu ra. Loader: transform files (babel-loader, css-loader). Plugin: mở rộng chức năng (HtmlWebpackPlugin, MiniCssExtractPlugin).',
    hints: ['Đề cập đến tree shaking, code splitting', 'So sánh với Vite nếu biết'],
  },
  {
    content: 'TypeScript mang lại lợi ích gì so với JavaScript thuần? Giải thích về generics và type guards.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'TypeScript',
    role: 'FE',
    level: 'junior',
    tags: ['typescript', 'types', 'generics', 'frontend'],
    expectedDuration: 120,
    sampleAnswer: 'TypeScript: type safety, better IDE support, catch bugs compile time. Generics cho phép tái sử dụng code với nhiều type. Type guards (typeof, instanceof, custom) narrow type trong runtime.',
    hints: ['Nêu ví dụ generic function cụ thể', 'Đề cập đến type vs interface'],
  },
  {
    content: 'React component lifecycle hoạt động như thế nào? So sánh class component lifecycle với hooks.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'React',
    role: 'FE',
    level: 'junior',
    tags: ['react', 'lifecycle', 'hooks', 'useEffect'],
    expectedDuration: 120,
    sampleAnswer: 'Class: constructor → render → componentDidMount → componentDidUpdate → componentWillUnmount. Hooks: useEffect(() => {}, []) tương đương didMount, useEffect(() => {}, [dep]) tương đương didUpdate, cleanup function tương đương willUnmount.',
    hints: ['Vẽ sơ đồ lifecycle nếu có thể', 'Giải thích dependency array của useEffect'],
  },
  {
    content: 'Giải thích cách hoạt động của this trong JavaScript. Sự khác biệt giữa arrow function và regular function.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'JavaScript',
    role: 'FE',
    level: 'junior',
    tags: ['javascript', 'this', 'arrow function', 'scope'],
    expectedDuration: 120,
    sampleAnswer: 'this trong regular function phụ thuộc vào cách gọi (implicit, explicit binding, new). Arrow function không có this riêng, kế thừa từ lexical scope. Không dùng arrow function làm method của object.',
    hints: ['Nêu 4 rules binding: default, implicit, explicit, new', 'Ví dụ về call, apply, bind'],
  },
  {
    content: 'Web Performance Optimization: những kỹ thuật nào bạn thường dùng để tối ưu tốc độ tải trang?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Performance',
    role: 'FE',
    level: 'senior',
    tags: ['performance', 'optimization', 'frontend', 'web vitals'],
    expectedDuration: 150,
    sampleAnswer: 'Code splitting, lazy loading, image optimization (WebP, srcset), caching (HTTP cache, Service Worker), minification, tree shaking, CDN, preload/prefetch, reduce render-blocking resources.',
    hints: ['Đề cập đến Core Web Vitals (LCP, FID, CLS)', 'Nêu tools đo lường (Lighthouse, WebPageTest)'],
  },

  // ─────────────────────────────────────────
  // TECHNICAL — BACKEND (15) — role: BE
  // ─────────────────────────────────────────
  {
    content: 'REST API là gì? Giải thích các nguyên tắc RESTful và sự khác biệt với GraphQL.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'API Design',
    role: 'BE',
    level: 'fresher',
    tags: ['rest', 'api', 'http', 'graphql', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'REST: stateless, uniform interface, resource-based URL, HTTP methods. GraphQL: query linh hoạt, single endpoint, tránh over/under-fetching. REST phù hợp với public API, GraphQL tốt cho complex data requirements.',
    hints: ['Giải thích 6 constraints của REST', 'Nêu ví dụ URL design tốt vs xấu'],
  },
  {
    content: 'Database indexing hoạt động như thế nào? Khi nào nên và không nên tạo index?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    role: 'BE',
    level: 'junior',
    tags: ['database', 'index', 'performance', 'mongodb', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'Index là cấu trúc dữ liệu (B-tree) tăng tốc query. Nên index: fields thường query/sort/join. Không nên: bảng nhỏ, fields ít unique, bảng thường xuyên write nhiều (index làm chậm write).',
    hints: ['Giải thích B-tree index', 'Đề cập đến compound index và selectivity'],
  },
  {
    content: 'SQL vs NoSQL: khi nào chọn cái nào? Ưu nhược điểm của mỗi loại.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    role: 'BE',
    level: 'junior',
    tags: ['sql', 'nosql', 'database', 'mongodb', 'postgresql'],
    expectedDuration: 120,
    sampleAnswer: 'SQL: ACID, schema cứng, quan hệ phức tạp, reporting. NoSQL: schema linh hoạt, scale horizontal, dữ liệu phi cấu trúc/semi-structured. Chọn dựa trên data model, query pattern, consistency requirements.',
    hints: ['Nêu ví dụ use case cụ thể cho mỗi loại', 'Đề cập đến CAP theorem'],
  },
  {
    content: 'Middleware trong Express.js là gì? Giải thích request lifecycle và cách error handling middleware hoạt động.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'Node.js',
    role: 'BE',
    level: 'fresher',
    tags: ['nodejs', 'express', 'middleware', 'backend'],
    expectedDuration: 90,
    sampleAnswer: 'Middleware là function có (req, res, next). Được thực thi theo thứ tự. Error middleware có 4 params (err, req, res, next). Request đi qua từng middleware theo thứ tự mount.',
    hints: ['Vẽ flow của request qua các middleware', 'Đề cập đến next(err) để pass lỗi'],
  },
  {
    content: 'Caching là gì? Giải thích các loại cache và chiến lược cache invalidation.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Caching',
    role: 'BE',
    level: 'junior',
    tags: ['cache', 'redis', 'performance', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'Cache-aside, Read-through, Write-through, Write-behind. Invalidation: TTL-based, event-driven, cache busting. Redis cho distributed cache. Vấn đề: cache stampede, thundering herd, stale data.',
    hints: ['Giải thích trade-off giữa consistency và performance', 'Đề cập đến CDN cache vs application cache'],
  },
  {
    content: 'ACID properties trong database là gì? Giải thích transaction và isolation levels.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Database',
    role: 'BE',
    level: 'senior',
    tags: ['database', 'acid', 'transaction', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Atomicity: tất cả hoặc không. Consistency: data luôn valid. Isolation: transaction không ảnh hưởng nhau. Durability: data persist sau commit. Isolation levels: Read Uncommitted, Read Committed, Repeatable Read, Serializable.',
    hints: ['Nêu ví dụ về dirty read, phantom read', 'Giải thích trade-off giữa isolation và performance'],
  },
  {
    content: 'N+1 query problem là gì? Làm thế nào để phát hiện và giải quyết?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    role: 'BE',
    level: 'junior',
    tags: ['database', 'n+1', 'orm', 'performance', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'N+1: 1 query lấy N records, sau đó N queries cho mỗi record (tổng N+1 queries). Giải quyết: eager loading (populate/join), dataloader (batch), denormalization. Phát hiện bằng query logger.',
    hints: ['Nêu ví dụ cụ thể với code', 'Đề cập đến Mongoose populate vs aggregation'],
  },
  {
    content: 'Message Queue là gì? Khi nào nên dùng? So sánh Bull, RabbitMQ và Kafka.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Message Queue',
    role: 'BE',
    level: 'senior',
    tags: ['queue', 'bull', 'rabbitmq', 'kafka', 'async', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Queue: decouple services, handle async tasks, retry failed jobs. Bull: đơn giản, Redis-based, tốt cho Node.js. RabbitMQ: reliable messaging, routing phức tạp. Kafka: high throughput, event streaming, replay.',
    hints: ['Đề cập đến dead letter queue, retry mechanism', 'Nêu ví dụ use case: email, notification, video processing'],
  },
  {
    content: 'JWT (JSON Web Token) hoạt động như thế nào? Sự khác biệt giữa access token và refresh token.',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Authentication',
    role: 'BE',
    level: 'junior',
    tags: ['jwt', 'auth', 'security', 'token', 'backend'],
    expectedDuration: 120,
    sampleAnswer: 'JWT gồm header.payload.signature. Stateless, không cần store session. Access token: short-lived, dùng mỗi request. Refresh token: long-lived, chỉ dùng để lấy access token mới. Store refresh token ở httpOnly cookie.',
    hints: ['Giải thích tại sao không nên store JWT ở localStorage', 'Đề cập đến token rotation'],
  },
  {
    content: 'Rate limiting là gì? Giải thích các thuật toán: Token Bucket, Fixed Window, Sliding Window.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'API Security',
    role: 'BE',
    level: 'senior',
    tags: ['rate limit', 'security', 'algorithm', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Fixed Window: đếm requests trong window cố định, vấn đề burst ở ranh giới. Sliding Window: chính xác hơn, tốn memory hơn. Token Bucket: flexible, cho phép burst nhỏ. Leaky Bucket: smooth out traffic.',
    hints: ['Vẽ diagram cho từng thuật toán', 'Đề cập đến distributed rate limiting với Redis'],
  },
  {
    content: 'Connection pooling là gì? Tại sao quan trọng và cách config pool size tối ưu?',
    category: 'technical',
    difficulty: 'medium',
    topic: 'Database',
    role: 'BE',
    level: 'junior',
    tags: ['connection pool', 'database', 'performance', 'backend'],
    expectedDuration: 90,
    sampleAnswer: 'Pool giữ sẵn N connections để tái sử dụng, tránh overhead tạo connection mới. Pool size tối ưu phụ thuộc vào: số CPU, query duration, concurrency. Formula: pool_size = (core_count * 2) + effective_spindle_count.',
    hints: ['Giải thích overhead của việc tạo DB connection', 'Đề cập đến connection timeout, idle timeout'],
  },
  {
    content: 'Giải thích microservices architecture. Ưu nhược điểm so với monolithic và khi nào nên migrate?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Architecture',
    role: 'BE',
    level: 'senior',
    tags: ['microservices', 'monolith', 'architecture', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Microservices: independent deploy, scale riêng từng service, polyglot. Nhược: distributed system complexity, network latency, eventual consistency. Monolith: đơn giản hơn khi team nhỏ. Migrate khi team lớn, domain rõ ràng.',
    hints: ['Đề cập đến service discovery, API gateway', 'Nêu Domain-Driven Design trong context microservices'],
  },
  {
    content: 'OAuth 2.0 flow hoạt động như thế nào? Giải thích Authorization Code Flow và khi nào dùng các grant types khác.',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Authentication',
    role: 'BE',
    level: 'senior',
    tags: ['oauth', 'security', 'auth', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Authorization Code: FE redirect → provider → callback với code → BE đổi code lấy token. Client Credentials: service-to-service. Device Code: TV/IoT. PKCE: cho public clients (SPA, mobile).',
    hints: ['Giải thích tại sao code flow an toàn hơn implicit', 'Đề cập đến PKCE'],
  },
  {
    content: 'Làm thế nào để handle database migration an toàn trên production không downtime?',
    category: 'technical',
    difficulty: 'hard',
    topic: 'Database',
    role: 'BE',
    level: 'senior',
    tags: ['migration', 'database', 'deployment', 'backend'],
    expectedDuration: 150,
    sampleAnswer: 'Expand-contract pattern: thêm column mới → deploy code hỗ trợ cả 2 → backfill data → remove column cũ. Tránh rename/drop trực tiếp. Feature flags để kiểm soát rollout. Blue-green deployment.',
    hints: ['Đề cập đến backward compatibility', 'Nêu ví dụ với rename column'],
  },
  {
    content: 'Giải thích các HTTP status codes phổ biến. Sự khác biệt giữa 401 vs 403, 400 vs 422, 503 vs 504.',
    category: 'technical',
    difficulty: 'easy',
    topic: 'HTTP',
    role: 'BE',
    level: 'fresher',
    tags: ['http', 'status code', 'rest', 'backend'],
    expectedDuration: 90,
    sampleAnswer: '401 Unauthorized: chưa xác thực. 403 Forbidden: đã xác thực nhưng không có quyền. 400 Bad Request: syntax sai. 422 Unprocessable Entity: syntax đúng nhưng semantic sai. 503 Service Unavailable. 504 Gateway Timeout.',
    hints: ['Phân nhóm 2xx, 3xx, 4xx, 5xx', 'Nêu context sử dụng đúng trong API design'],
  },

  // ─────────────────────────────────────────
  // SYSTEM DESIGN (20) — role: FS
  // ─────────────────────────────────────────
  {
    content: 'Thiết kế hệ thống rút ngắn URL (URL Shortener) như bit.ly. Xử lý 100M URLs và 10B redirects/tháng.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'url shortener', 'hashing', 'database'],
    expectedDuration: 1800,
    sampleAnswer: 'Clarify requirements → Estimation → High-level design: API, DB schema. Hash function (Base62, 7 chars = 62^7 = 3.5T). DB: Write path (generate + store), Read path (cache-heavy). Redis cache 20% hot URLs. CDN cho redirect.',
    hints: ['Bắt đầu bằng clarify requirements và estimation', 'Thảo luận về hash collision handling'],
  },
  {
    content: 'Thiết kế hệ thống chat real-time như Messenger. Hỗ trợ 1-1 và group chat, online presence.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'chat', 'websocket', 'real-time'],
    expectedDuration: 1800,
    sampleAnswer: 'WebSocket cho persistent connection. Chat service, Presence service riêng. Message storage: Cassandra (high write throughput). Media: S3. Fan-out: cho group chat dùng message queue. End-to-end encryption.',
    hints: ['Phân biệt 1-1 vs group chat fan-out strategy', 'Đề cập đến offline message delivery'],
  },
  {
    content: 'Thiết kế hệ thống newsfeed của mạng xã hội (như Facebook). Hỗ trợ 1B users, 1M posts/ngày.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'newsfeed', 'fan-out', 'social media'],
    expectedDuration: 1800,
    sampleAnswer: 'Fan-out on write (push model) cho users bình thường. Fan-out on read (pull model) cho celebrities (nhiều followers). Hybrid approach. Redis sorted set cho feed. Ranking service. Pagination với cursor.',
    hints: ['Thảo luận trade-off giữa push vs pull model', 'Đề cập đến celebrity problem'],
  },
  {
    content: 'Thiết kế hệ thống notification. Hỗ trợ push notification, email, SMS cho 100M users.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'notification', 'push', 'email', 'queue'],
    expectedDuration: 1800,
    sampleAnswer: 'Notification service nhận event → Message Queue (phân loại theo channel) → Workers (email/push/SMS). Rate limiting per user. Template engine. Retry mechanism. User preference (do not disturb). Analytics tracking.',
    hints: ['Đề cập đến delivery guarantee (at-least-once, exactly-once)', 'Thảo luận về priority queue'],
  },
  {
    content: 'Thiết kế hệ thống lưu trữ file như Dropbox/Google Drive. Upload/download file lớn, sync across devices.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'storage', 'file upload', 's3'],
    expectedDuration: 1800,
    sampleAnswer: 'Chunk file thành 4MB blocks, dedup bằng hash. Upload: presigned URL lên S3 trực tiếp. Metadata service (DB). Sync service với delta sync. CDN cho download. Versioning. Conflict resolution.',
    hints: ['Giải thích chunking và deduplication', 'Đề cập đến delta sync để giảm bandwidth'],
  },
  {
    content: 'Thiết kế hệ thống search autocomplete (typeahead). Mỗi ký tự gõ trả về 5 gợi ý trong < 100ms.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'search', 'trie', 'autocomplete'],
    expectedDuration: 1800,
    sampleAnswer: 'Trie data structure hoặc prefix hash. Offline job tính tần suất từ search logs. Cache hot prefixes. Trie sharding theo prefix. Trie serialization. Personalization layer nếu cần.',
    hints: ['So sánh Trie vs Elasticsearch', 'Đề cập đến cách update Trie mà không downtime'],
  },
  {
    content: 'Thiết kế hệ thống thanh toán (Payment System). Đảm bảo exactly-once processing, idempotency.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'payment', 'idempotency', 'transaction'],
    expectedDuration: 1800,
    sampleAnswer: 'Idempotency key cho mỗi transaction. Double-entry bookkeeping. Distributed transaction (2PC hoặc Saga pattern). Reconciliation job. PCI DSS compliance. Retry với exponential backoff. Immutable event log.',
    hints: ['Tại sao idempotency quan trọng', 'Giải thích Saga pattern để tránh distributed transaction'],
  },
  {
    content: 'Thiết kế hệ thống streaming video như YouTube. Upload, transcode, deliver video đến hàng triệu users.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'video', 'streaming', 'cdn', 'transcoding'],
    expectedDuration: 1800,
    sampleAnswer: 'Upload: chunked upload → S3. Transcoding pipeline (queue + workers) → nhiều resolution. Storage: S3 cho original, CDN edge servers cho delivery. Adaptive bitrate streaming (HLS/DASH). Metadata DB.',
    hints: ['Đề cập đến adaptive bitrate streaming', 'Thảo luận về CDN cache strategy cho video'],
  },
  {
    content: 'Thiết kế Rate Limiter cho API Gateway. Hỗ trợ nhiều thuật toán, distributed system.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'rate limiter', 'redis', 'algorithm'],
    expectedDuration: 1800,
    sampleAnswer: 'Rules engine (lấy từ DB/cache). Redis cho distributed counter. Algorithms: Token Bucket (default), Sliding Window Log, Fixed Window Counter. Header trả về remaining/reset. Soft vs hard limit. Race condition với Lua script.',
    hints: ['Giải thích race condition trong distributed rate limiter', 'Đề cập đến Redis Lua script để atomic operations'],
  },
  {
    content: 'Thiết kế hệ thống distributed cache. So sánh với Redis và khi nào tự build vs dùng off-the-shelf.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'cache', 'distributed', 'redis'],
    expectedDuration: 1800,
    sampleAnswer: 'Consistent hashing để distribute keys. Replication cho availability. Eviction policies (LRU, LFU). Cache coherence problem. Write-through vs write-behind. Hot key problem. Thundering herd protection.',
    hints: ['Giải thích consistent hashing và virtual nodes', 'Thảo luận về hot key problem và solutions'],
  },
  {
    content: 'Thiết kế hệ thống recommendation cho e-commerce. Gợi ý sản phẩm dựa trên lịch sử user.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'recommendation', 'ml', 'collaborative filtering'],
    expectedDuration: 1800,
    sampleAnswer: 'Collaborative filtering (user-based, item-based). Content-based filtering. Hybrid approach. Offline training (Spark). Online serving (feature store, model server). A/B testing framework. Cold start problem cho new users.',
    hints: ['Giải thích cold start problem', 'Đề cập đến online vs offline model serving'],
  },
  {
    content: 'Thiết kế real-time leaderboard cho game. Cập nhật score liên tục, query top 10 trong < 10ms.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'leaderboard', 'redis', 'sorted set'],
    expectedDuration: 1800,
    sampleAnswer: 'Redis Sorted Set: ZADD O(log N), ZRANGE O(log N + K). Shard theo game room hoặc time window. Periodic snapshot sang DB. Global leaderboard: merge top-K từ shards. Rank cho user cụ thể: ZRANK.',
    hints: ['Tại sao Redis Sorted Set phù hợp', 'Thảo luận về global vs local leaderboard'],
  },
  {
    content: 'Thiết kế hệ thống logging và monitoring tập trung cho microservices. ELK stack.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'logging', 'monitoring', 'elk', 'observability'],
    expectedDuration: 1800,
    sampleAnswer: 'Log collection (Filebeat/Fluentd) → Kafka → Logstash → Elasticsearch → Kibana. Structured logging (JSON). Correlation ID cho distributed tracing. Metrics (Prometheus + Grafana). Alerting rules. Log retention policy.',
    hints: ['Giải thích 3 pillars of observability: logs, metrics, traces', 'Đề cập đến sampling cho high-traffic'],
  },
  {
    content: 'Thiết kế API Gateway. Xử lý authentication, routing, load balancing, circuit breaker.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'api gateway', 'load balancer', 'circuit breaker'],
    expectedDuration: 1800,
    sampleAnswer: 'Auth middleware (JWT verify). Dynamic routing table. Load balancing (round robin, least connections, weighted). Circuit breaker (Closed/Open/Half-Open). Rate limiting. Request/response transformation. Service discovery integration.',
    hints: ['Giải thích circuit breaker pattern', 'Đề cập đến service mesh vs API gateway'],
  },
  {
    content: 'Thiết kế ứng dụng đặt xe như Grab/Uber. Matching driver-rider, real-time location tracking.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'uber', 'geospatial', 'matching', 'real-time'],
    expectedDuration: 1800,
    sampleAnswer: 'Location service: driver cập nhật vị trí mỗi 5s (WebSocket). Geospatial index (Quadtree, Geohash). Matching service: tìm driver gần nhất → ETA calculation. Surge pricing. Trip lifecycle state machine.',
    hints: ['Giải thích Geohash và Quadtree', 'Thảo luận về matching algorithm trade-offs'],
  },
  {
    content: 'Thiết kế hệ thống đặt phòng khách sạn như Booking.com. Tránh double-booking, giá động.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'booking', 'concurrency', 'inventory'],
    expectedDuration: 1800,
    sampleAnswer: 'Inventory service với optimistic locking. Reserve → Checkout flow với timeout. Idempotent booking. Search: Elasticsearch với availability filter. Pricing service (rule-based + demand). Distributed lock với Redis cho peak time.',
    hints: ['Giải thích optimistic vs pessimistic locking', 'Đề cập đến overbooking strategy'],
  },
  {
    content: 'Thiết kế hệ thống CDN (Content Delivery Network). Cách cache và invalidate content.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'cdn', 'cache', 'content delivery'],
    expectedDuration: 1800,
    sampleAnswer: 'Edge servers tại nhiều PoPs. Anycast routing. Cache hierarchy (L1 edge → L2 regional → origin). Cache key design. TTL-based invalidation. Purge API. Cache miss: request to origin, cache the response. HTTPS termination at edge.',
    hints: ['Giải thích Anycast và BGP routing', 'Thảo luận về cache key design'],
  },
  {
    content: 'Thiết kế hệ thống CI/CD pipeline. Từ code commit đến production deployment không downtime.',
    category: 'situational',
    difficulty: 'medium',
    topic: 'System Design',
    role: 'FS',
    level: 'middle',
    tags: ['system design', 'cicd', 'deployment', 'devops'],
    expectedDuration: 1800,
    sampleAnswer: 'Trigger: git push → Build (Docker image) → Test (unit, integration, e2e) → Security scan → Staging deploy → Smoke test → Blue-green production deploy → Health check → Auto-rollback on failure. Feature flags.',
    hints: ['Giải thích blue-green vs canary deployment', 'Đề cập đến rollback strategy'],
  },
  {
    content: 'Thiết kế hệ thống distributed search engine như Elasticsearch. Indexing, sharding, replication.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'search engine', 'elasticsearch', 'inverted index'],
    expectedDuration: 1800,
    sampleAnswer: 'Inverted index: term → list of document IDs. Sharding theo document ID (routing). Replication (primary + replicas). Index lifecycle management. Relevance scoring (TF-IDF, BM25). Near real-time indexing. Bulk API.',
    hints: ['Giải thích inverted index', 'Thảo luận về index vs query time relevance tuning'],
  },
  {
    content: 'Thiết kế hệ thống web crawler. Crawl 1B trang web, xử lý duplicate, robots.txt.',
    category: 'situational',
    difficulty: 'hard',
    topic: 'System Design',
    role: 'FS',
    level: 'senior',
    tags: ['system design', 'crawler', 'distributed', 'bfs'],
    expectedDuration: 1800,
    sampleAnswer: 'Seed URLs → Priority Queue (politeness, freshness) → Fetcher workers → Content parser → URL extractor → Dedup (Bloom filter) → Storage (S3). DNS cache. Rate limiting per domain. robots.txt compliance. Checksum dedup.',
    hints: ['Giải thích Bloom filter cho URL deduplication', 'Thảo luận về politeness và crawl rate limiting'],
  },

  // ─────────────────────────────────────────
  // HR — INTERN FOCUS (10)
  // role: General, level: intern
  // ─────────────────────────────────────────
  {
    content: 'Bạn biết gì về vị trí intern Software Engineer tại công ty? Kỳ vọng của bạn là gì?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Role Understanding',
    role: 'General',
    level: 'intern',
    tags: ['intern', 'expectations', 'role', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả hiểu biết về vị trí: hỗ trợ develop features, fix bugs, học codebase và quy trình làm việc. Kỳ vọng: được mentoring, học tech stack thực tế, đóng góp được cho team. Thể hiện realistic và học-hỏi mindset.',
    hints: ['Research JD kỹ trước', 'Thể hiện sẵn sàng học, không kỳ vọng quá cao'],
  },
  {
    content: 'Bạn có thể bắt đầu intern từ khi nào? Bạn có thể intern full-time hay part-time?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Availability',
    role: 'General',
    level: 'intern',
    tags: ['availability', 'schedule', 'intern', 'hr'],
    expectedDuration: 60,
    sampleAnswer: 'Trả lời thẳng về lịch học, khả năng thời gian. Nếu còn học: nêu rõ số ngày/tuần có thể đi. Nếu sắp tốt nghiệp: nêu ngày tốt nghiệp và khả năng full-time sau đó. Thể hiện tính linh hoạt.',
    hints: ['Trả lời rõ ràng, không mơ hồ về lịch trình', 'Đề cập đến khả năng làm full-time sau tốt nghiệp'],
  },
  {
    content: 'Môi trường làm việc lý tưởng của bạn trông như thế nào?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Work Environment',
    role: 'General',
    level: 'intern',
    tags: ['culture', 'work environment', 'preference', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Mô tả môi trường bạn học tốt nhất: có mentoring, feedback thường xuyên, code review, thoải mái đặt câu hỏi, teamwork. Kết nối với những gì bạn biết về văn hóa công ty.',
    hints: ['Research culture công ty trước', 'Tập trung vào môi trường học tập, không chỉ tiện ích (snacks, ping pong)'],
  },
  {
    content: 'Bạn đã từng làm intern hoặc part-time ở đâu chưa? Kể về kinh nghiệm đó.',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Work Experience',
    role: 'General',
    level: 'intern',
    tags: ['experience', 'intern', 'background', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Nếu có: mô tả công ty, công việc bạn làm, điều bạn học được, impact bạn tạo ra. Nếu chưa: thành thật, nhấn mạnh vào các project cá nhân/trường thay thế. Không cần experience để apply intern.',
    hints: ['Dự án trường hoặc cá nhân cũng có giá trị', 'Thành thật nếu chưa có kinh nghiệm'],
  },
  {
    content: 'Bạn biết đến công ty chúng tôi và vị trí này qua kênh nào?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Company Research',
    role: 'General',
    level: 'intern',
    tags: ['company research', 'networking', 'job search', 'hr'],
    expectedDuration: 60,
    sampleAnswer: 'Nêu cụ thể nguồn: LinkedIn, ITviec, TopCV, giới thiệu từ bạn bè, tech community, company blog... Thể hiện bạn đã research thêm về công ty sau khi biết. Thể hiện genuine interest.',
    hints: ['Nêu cụ thể, không nói chung chung', 'Đề cập đến điều gì khiến bạn apply sau khi research'],
  },
  {
    content: 'Bạn muốn phát triển theo hướng nào sau khi intern: Frontend, Backend, hay Fullstack?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Career Direction',
    role: 'General',
    level: 'intern',
    tags: ['career', 'direction', 'fe', 'be', 'fs', 'intern', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Chia sẻ định hướng và lý do: FE nếu thích UI/UX interaction, BE nếu thích data/logic/system, FS nếu muốn hiểu toàn bộ system. Thể hiện đây là suy nghĩ có cơ sở từ việc bạn đã thử cả hai.',
    hints: ['Tránh nói "tôi chưa biết" — thể hiện có suy nghĩ về định hướng', 'Kết nối với skills bạn đã học'],
  },
  {
    content: 'Khó khăn lớn nhất bạn gặp phải khi học lập trình là gì? Bạn vượt qua nó như thế nào?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Learning Challenges',
    role: 'General',
    level: 'intern',
    tags: ['challenges', 'learning', 'persistence', 'intern', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Chia sẻ thành thật: hiểu con trỏ/recursion, debug không có error message, học framework mới... Quan trọng hơn: mô tả cách bạn vượt qua (kiên trì, tìm resources, hỏi community). Thể hiện growth mindset.',
    hints: ['Thành thật về khó khăn', 'Tập trung vào cách bạn vượt qua, không chỉ nêu khó khăn'],
  },
  {
    content: 'Bạn thường học lập trình qua những nguồn tài liệu nào? (YouTube, sách, online courses, docs...)',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Learning Resources',
    role: 'General',
    level: 'intern',
    tags: ['learning', 'resources', 'self-study', 'intern', 'hr'],
    expectedDuration: 60,
    sampleAnswer: 'Nêu cụ thể: freeCodeCamp, Udemy, official docs (MDN, React docs), YouTube (Traversy Media, Fireship...), sách (You Don\'t Know JS), Stack Overflow, GitHub. Thể hiện bạn biết cách tự tìm kiếm và học.',
    hints: ['Nêu ít nhất 3-4 nguồn cụ thể', 'Đề cập đến official docs — thể hiện tính chuyên nghiệp'],
  },
  {
    content: 'Nếu được nhận vào intern, mục tiêu học tập của bạn trong 3 tháng đầu là gì?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Goals Setting',
    role: 'General',
    level: 'intern',
    tags: ['goals', 'planning', 'intern', 'learning', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Mục tiêu SMART: tháng 1 — hiểu codebase và quy trình, hoàn thành task nhỏ độc lập. Tháng 2 — contribute feature, ít hỏi hơn. Tháng 3 — tự handle task vừa, có thể review code junior. Thể hiện tự chủ và tham vọng hợp lý.',
    hints: ['Mục tiêu cụ thể, có thể đo lường', 'Thể hiện muốn tự chủ, không phụ thuộc quá nhiều'],
  },
  {
    content: 'Bạn nghĩ kỹ năng quan trọng nhất của một Software Engineer intern là gì?',
    category: 'hr',
    difficulty: 'easy',
    topic: 'Self-Awareness',
    role: 'General',
    level: 'intern',
    tags: ['skills', 'intern', 'soft skills', 'self-awareness', 'hr'],
    expectedDuration: 90,
    sampleAnswer: 'Một số kỹ năng quan trọng: học nhanh và chủ động, giao tiếp rõ ràng khi stuck, Google và đọc docs trước khi hỏi, chú ý đến detail, không ngại hỏi khi thực sự cần. Technical skill quan trọng nhưng attitude quan trọng hơn.',
    hints: ['Kết hợp cả technical và soft skills', 'Thể hiện bạn hiểu rằng intern là giai đoạn học, không phải chứng minh'],
  },
];

const seedQuestions = async () => {
  try {
    const count = await Question.countDocuments();
    if (count > 0) {
      // Chỉ xóa text questions, giữ nguyên coding questions
      const deleted = await Question.deleteMany({ type: { $ne: 'coding' } });
      console.log(`[Seeder] Dropped ${deleted.deletedCount} text questions for re-seed.`);
    }

    await Question.insertMany(questions);
    console.log(`[Seeder] Seeded ${questions.length} questions successfully.`);
  } catch (err) {
    console.error('[Seeder] Failed to seed questions:', err.message);
  }
};

module.exports = seedQuestions;
